### ISSUE TITLE
Usefull C and C++ examples for OpenGL apps

### ISSUE THREAD

**Issue by Symbian9** [whitequark/solvespace#102]
There are some usefull examples designed by Soji Yamakawa specially for his OpenGL-based flight simulator, that can be used in any purpose:
1) http://ysflight.in.coocan.jp/programming/uglyfont/uglyfonte.html
2) http://ysflight.in.coocan.jp/programming/uglyfont2/e.html
3) http://ysflight.in.coocan.jp/programming/fssimplewindow/e.html
4) http://ysflight.in.coocan.jp/programming/pngdecoder/pngdecodere.html

**Comment by Evil-Spirit** [comment]
@Symbian9 and?

**Comment by whitequark** [comment]
Nothing useful here.
