### ISSUE TITLE
DXF import

### ISSUE THREAD

**Issue by whitequark** [whitequark/solvespace#106]
Much-requested feature: http://solvespace.com/forum.pl?action=viewthread&parent=24 and not too hard with the new DXF library. Let's do it in 2.1.

**Comment by Evil-Spirit** [comment]
Ok, its no problem with it.

**Comment by whitequark** [comment]
In the menu we can put it under `File → Import...`.

**Comment by Symbian9** [comment]
@whitequark, you mean "Menu -> New Group -> Import / Assemble..."?

**Comment by whitequark** [comment]
No. That's for linking other files and tracking changes in them. This DXF import feature will not do that.

**Comment by Evil-Spirit** [comment]
@Symbian9, I don't think so, the svg is pure graphical format, there is no any usecase when it can be applicable.

**Comment by whitequark** [comment]
No, I'm not interested in SVG.

**Comment by Evil-Spirit** [comment]
![2016-04-14 17 43 03](https://cloud.githubusercontent.com/assets/1980537/14526944/7e930dd4-0268-11e6-9f24-09c614945ca9.png)

**Comment by Evil-Spirit** [comment]
![2016-04-14 17 47 11](https://cloud.githubusercontent.com/assets/1980537/14527013/f951899c-0268-11e6-9e20-e726389e176e.png)

**Comment by Symbian9** [comment]
@EvilSpirit, COOL! When i can test this nightly?

**Comment by Evil-Spirit** [comment]
When i done.  You can send me dikes which you want to import

**Comment by Evil-Spirit** [comment]
When i done. You can send me files which you want to import

**Comment by Symbian9** [comment]
@Evil-Spirit, did you try make sketch -> export to DXF -> open in LibreCAD & resave in other DXF -> and then import it to SolveSpace again?

**Comment by Evil-Spirit** [comment]
Round-trip
![2016-04-14 22 32 22](https://cloud.githubusercontent.com/assets/1980537/14535694/dc39dcba-0290-11e6-923c-50bca70dbb7a.png)

**Comment by Symbian9** [comment]
@Evil-Spirit, what going with circles and arcs after this "round trip"?
As I can see, there some segmented circles or you did some settings for chord tolerance?

**Comment by Evil-Spirit** [comment]
@Symbian9, this is just because chord tolerance, one of acrs has very far-distanted center-point, so the chord tol is too big.

**Comment by Symbian9** [comment]
@Evil-Spirit, no. Circle in SolveSpace include only 1 point at center.
On your "round-trip" screen I see circle with 5 points, so something wrong with it!

**Comment by Evil-Spirit** [comment]
Circles just becomes an arcs. This is an export issue, not the import.

**Comment by Evil-Spirit** [comment]
@Symbian9, just learn how to build it yourself.

**Comment by Evil-Spirit** [comment]
Sample with splines:
![2016-04-15 22 19 24](https://cloud.githubusercontent.com/assets/1980537/14567944/5f4ecd00-0358-11e6-9acf-6d65480b0751.png)

**Comment by whitequark** [comment]
@Evil-Spirit Are you done with this, or is there something else?

**Comment by whitequark** [comment]
@jwesthues Where do you think the menu item should be? I feel like we need to distinguish the existing `Import / Assemble` command which does a linked import, and this new command, which does a non-linked import. I think it should be put under `File` as `Import...`, and `Import / Assemble` should be renamed to `Link / Assemble` to better describe the function that it performs. I think it also makes sense, in the future, to do allow to link in DXFs.

**Comment by jwesthues** [comment]
All of that make sense to me. Linked DXF import is potentially a rather complicated problem, since for any constraints against the linked entities to work usefully, you'd need heuristics to consistently assign identifiers to the imported entities.

**Comment by whitequark** [comment]
> you'd need heuristics to consistently assign identifiers to the imported entities.

Yeah. The idea was to use the handles in DXF files to generate entity IDs. Handle reuse is a problem, but then it is also a problem for linking sketches...

**Comment by Evil-Spirit** [comment]
@whitequark, this depend of how deep we have to go.
There is basic entities imported;

Need to import:
* text
* textstyles

What to do with:
* dimensions
* blocks
* layers
* ltypes

**Comment by whitequark** [comment]
> blocks

For now: expand them. Expand them inline every time they're used.

> layers, ltypes

How about this: take the entire set of styles we care about from both the layer and the entity, merge them, and squash it into a string. E.g. `0.1-continuous-ff0000` or something like that. Then either create a new custom style with that name or reuse one if it already exists, even if the style has different actual attributes--this way it would be easy to remap attributes on several DXF files imported one after another.

> dimensions

When we can determine exactly that a diameter or an angular dimension constrains specific points, then a constraint should be created for those. When we cannot, increment a counter and then display a message saying "n constraints from the imported file were discarded".

But on top of that, we should infer the following constraints from *geometry*:

  * Point-coincident
  * Horizontal
  * Vertical

All of the above are unambiguous and they won't result in sketches that can't solve, so we can safely do that. And it will be very convenient if one wants to maintain the drawing.

**Comment by Evil-Spirit** [comment]
@whitequark,
I thiking about autoconstraining coincident, horizontal and vertical (optional) and about dimensions which is exactly fit the entities, so we can constrain.

**Comment by Evil-Spirit** [comment]
@jwesthues , We really have the problem with solver which throws params not envolved in equations. 
Why we should do it? We just have no any constraints, but the solver overdriven (max params exceeded).

**Comment by jwesthues** [comment]
No reason beyond laziness; I'd intended SolveSpace for typical parametric modeling, where all (or almost all) parameters are constrained and this doesn't matter much. It makes sense to exclude parameters not mentioned in any equations from the Jacobian, a slight speedup even when you don't exceed `MAX_UNKNOWNS`.

**Comment by Symbian9** [comment]
Some DXF samples for testing
http://cadkit.blogspot.nl/p/sample-dxf-files.html

**Comment by Evil-Spirit** [comment]
@whitequark, how to commit libdxfrw?
```
    DRW_Spline(const DRW_Spline& p):DRW_Entity(p){
        eType        = DRW::SPLINE;
        normalVec    = p.normalVec ;
        tgStart      = p.tgStart   ;
        tgEnd        = p.tgEnd     ;
        flags        = p.flags     ;
        degree       = p.degree    ;
        nknots       = p.nknots    ;
        ncontrol     = p.ncontrol  ;
        nfit         = p.nfit      ;
        tolknot      = p.tolknot   ;
        tolcontrol   = p.tolcontrol;
        tolfit       = p.tolfit    ;
        
        for(double v : p.knotslist) knotslist.push_back(v);
        for(double v : p.weightlist) weightlist.push_back(v);
        for(DRW_Coord *v : p.controllist) controllist.push_back(new DRW_Coord(*v));
        for(DRW_Coord *v : p.fitlist) fitlist.push_back(new DRW_Coord(*v));
    }
```

**Comment by whitequark** [comment]
Just fork it, like with solvespace.

**Comment by Evil-Spirit** [comment]
@whitequark, may be just direct push into branches?

**Comment by whitequark** [comment]
Not for now.

**Comment by whitequark** [comment]
Specifically, I see code review as necessary before landing changes to `master`, and if you don't push into `master` then what difference does it make which repo it is?

**Comment by Evil-Spirit** [comment]
> push into branches
not master

i just don't know what is happening when i switch the main repo after switching submodule

**Comment by whitequark** [comment]
Ah... The submodule is, logically, a file with a commit hash. Once you commit it, it will stay at that hash, but other people won't be able to check out the submodule unless they do `git fetch git://github.com/evilspirit/libdxfrw` first.

**Comment by whitequark** [comment]
Let's work with forks for now. Once we get 2.1 out I'll think about switching to a more convenient workflow, now that we have the solvespace organization.

**Comment by Evil-Spirit** [comment]
What about making points like this?
![2016-04-22 13 31 26](https://cloud.githubusercontent.com/assets/1980537/14734783/a27e20c2-088e-11e6-9d14-81a83ce934f4.png)

**Comment by whitequark** [comment]
let's discuss it on IRC.

**Comment by Evil-Spirit** [comment]
> Some DXF samples for testing
http://cadkit.blogspot.nl/p/sample-dxf-files.html

@Symbian9, Thank you for useful examples. Can you say what kind of license it use and can i commit this into testcases repo? BTW, is there some dxf test-tables with all types of entities and all the parametes and cases used?

**Comment by Symbian9** [comment]
I found this link in at the end of README.md from LibreCAD
https://github.com/LibreCAD/LibreCAD_3/blob/master/README.md

Try ask it on LibreCAD project page, because I don't know what is the license

**Comment by whitequark** [comment]
@Evil-Spirit What's left here? Just automatically adding constraints?

**Comment by Evil-Spirit** [comment]
@whitequark, I almost done with constraints.

**Comment by Evil-Spirit** [comment]
![2016-04-26 12 11 21](https://cloud.githubusercontent.com/assets/1980537/14808570/21bd0530-0ba8-11e6-804a-cdd8bd459ed3.png)

**Comment by Evil-Spirit** [comment]
with autoconstraining(H/V, PC)
![2016-04-26 12 12 45](https://cloud.githubusercontent.com/assets/1980537/14808582/40bd9c4c-0ba8-11e6-9efd-08e8f4bd0b39.png)

**Comment by Evil-Spirit** [comment]
![2016-04-26 12 18 49](https://cloud.githubusercontent.com/assets/1980537/14808671/1cbc6eee-0ba9-11e6-8ecd-edefbe597f5d.png)

**Comment by whitequark** [comment]
Looks wonderful!

**Comment by Symbian9** [comment]
@Evil-Spirit, why all around in red?

**Comment by Evil-Spirit** [comment]
@Symbian9, solver can't create matrix for such big (MAX_UNKNOWNS exceeded). 
>No reason beyond laziness; I'd intended SolveSpace for typical parametric modeling, where all (or almost all) parameters are constrained and this doesn't matter much. It makes sense to exclude parameters not mentioned in any equations from the Jacobian, a slight speedup even when you don't exceed MAX_UNKNOWNS.

**Comment by Evil-Spirit** [comment]
@jwesthues,
But if we could remove problem with solver overdrive by params, not envolved in equations, we can make linear algorithm for SolveBySubstitution, and because H/V PC constraints not envolved into solving, we can solve sketches any size even with MAX_UNKNOWNS.

**Comment by whitequark** [comment]
Done in 70d84b3 and a21a327a, pending some details in #149.
