### ISSUE TITLE
Coincident points show "not all points are coplanar" message

### ISSUE THREAD

**Issue by whitequark** [whitequark/solvespace#107]
... which is wrong and confusing.

**Comment by whitequark** [comment]
Test case: press `S` then click two times at the exact same pixel.

There seems to be logic for `zero-length edge!` message but it's broken.

**Comment by Evil-Spirit** [comment]
So, should i do something with it? it seems need only to change message.

**Comment by whitequark** [comment]
Yes, only the message needs to be changed.

**Comment by whitequark** [comment]
Fixed in efb9fa3.
