### ISSUE TITLE
After removing "sketch in 3d", "sketch in plane" can be extruded

### ISSUE THREAD

**Issue by Symbian9** [whitequark/solvespace#108]
1) Add rectangle in plane
2) Use "Sketch in 3D"
3) Add point in 3D
4) Remove this point
5) Try "Extrude" presented rectangle
RESULT: now impossible extrude sketch in plane, but there no any sketch in 3D here

**Comment by whitequark** [comment]
Hm, not a bug. You simply have to do what the error message says:
```
Select a workplane (Sketch -> In Workplane) before
extruding. The sketch will be extruded normal to
the workplane.
```
