### ISSUE TITLE
Assign to other style measure constraints

### ISSUE THREAD

**Issue by Symbian9** [whitequark/solvespace#109]
For now some special marks (as "H", "V" and few other) there really no need to export in 2D Drawing.
But its impossible hide them separatly from other like angle constraint and length that preferable for printing. 
Think, it would be good, if it would be possible assign to other style some of constraints.
Also, in future it will help setup measure look exactly as drawing standarts
![Figure 23 - Dimensioned Drawing](http://www.me.umn.edu/courses/me2011/handouts/drawing/index_files/fig_23.jpeg)
http://www.me.umn.edu/courses/me2011/handouts/drawing/blanco-tutorial.html

**Comment by whitequark** [comment]
In the future SolveSpace will have a dedicated drawing module, which will solve this problem and others. However, we are many months away from this, so closing for now.

**Comment by Evil-Spirit** [comment]
We could support something like dxf dimstyle in order to support any standart (iso, ansi, gost, etc)

**Comment by Symbian9** [comment]
@Evil-Spirit, it would be cool if SolveSpace will have inbuild ISO and GOST technical and mechanical drawing standarts.
But anyway, some standarts can change from time to time, so need some advanced futures.

**Comment by Evil-Spirit** [comment]
Actually we can solve it by allowing styling the constraints
