### ISSUE TITLE
Stop using 80-symbols guideline.

### ISSUE THREAD

**Issue by Evil-Spirit** [whitequark/solvespace#110]
@whitequark,
@jwesthues,
I have the half of my sceen empty;
Why we need to do ugly line-breaks?
Could you enlarge your consoles under the linux?
![2016-04-13 10 59 43](https://cloud.githubusercontent.com/assets/1980537/14483316/84c43194-0167-11e6-9b44-8bca2246362f.png)
![2016-04-13 11 00 58](https://cloud.githubusercontent.com/assets/1980537/14483315/84c3e270-0167-11e6-8905-94e5cde0b6a4.png)
![2016-04-13 11 01 40](https://cloud.githubusercontent.com/assets/1980537/14483313/84c23a7e-0167-11e6-9d19-0a795e65a108.png)
![2016-04-13 11 03 11](https://cloud.githubusercontent.com/assets/1980537/14483314/84c23e3e-0167-11e6-8c2a-93e7c5ccb2ee.png)

**Comment by jwesthues** [comment]
That, I care less about. I very slightly prefer 80-column lines, but at your/whitequark's discretion (though I wouldn't count your second example as ugly, since it aligns two analogous things).

**Comment by Evil-Spirit** [comment]
Sorry, could we use at least 80 symbols before newline-breaking?

**Comment by jwesthues** [comment]
I mean if whitequark doesn't mind wider, I'm good with it.

**Comment by Evil-Spirit** [comment]
There is not so much cases when it really helps (like aligning inside function calls), but this is so ugly inside functions-prototypes.

**Comment by jwesthues** [comment]
If you want to go wider for new code (or as part of other changes) and whitequark doesn't mind, I don't object. Please don't make changes for formatting of existing code only, since that creates low-value churn.

**Comment by Evil-Spirit** [comment]
Ok, of course just for new or edited code;

**Comment by whitequark** [comment]
Is 100-characters ok? This is what I generally use for my other code.

**Comment by whitequark** [comment]
FWIW I don't believe in console editors. I'm using Sublime Text on a widescreen laptop and fitting 120 columns makes text a bit too small to comfortably read.

**Comment by Evil-Spirit** [comment]
ok, lets do 100.
