### ISSUE TITLE
Flip normal when extruding & using difference

### ISSUE THREAD

**Issue by pimdegroot** [whitequark/solvespace#116]
When using the extrude tool the default is to extrude outward with a union Boolean.

Switching to difference keeps the direction outward. What i would expect is that the direction flips inward so you can see that it makes a hole.

**Comment by whitequark** [comment]
I definitely see the issue--this is an extra action every time one creates a hole, and on large sketches can be quite slow, too, since you cannot readily constrain it in the right orientation while the normal points in the wrong direction, and so you have to wait for the solver many times.

However, I see a problem with your solution: if there are any constraints on any entities created by the extrusion, and it's flipped over, then the sketch may become quite broken.

**Comment by pimdegroot** [comment]
in that case make the default dimension negative when switching to difference, failing gracefully when there is a constraint preventing that.

**Comment by whitequark** [comment]
> in that case make the default dimension negative when switching to difference

There's no "default dimension" for extrusions--when they are not constrained they are simply free to move along all degrees of freedom they have, like everything else.

@jwesthues Any idea how to do this cleanly?

**Comment by jwesthues** [comment]
@whitequark Not really. You could flip the extrude vector only in special cases (totally unconstrained, one length dimension on line parallel to extrude direction, etc.), I guess.

**Comment by whitequark** [comment]
Okay. I think what I'll do is implement flipping for the case where no constraints mention the entities from the current group, to address the most common case: extruding something you immediately know should be a hole.

**Comment by Evil-Spirit** [comment]
@whitequark, can we just make one more button "create extruded hole" with "difference" by default and corresponding direction?

**Comment by whitequark** [comment]
What's the problem with flipping normal?

**Comment by Evil-Spirit** [comment]
@whitequark 
you just want to reverse extrusion every time when you switch between difference and other?

**Comment by whitequark** [comment]
Yep

**Comment by Evil-Spirit** [comment]
OK

**Comment by whitequark** [comment]
@Evil-Spirit Any progress on this?

**Comment by Evil-Spirit** [comment]
Not yet. I've just started after holydays, need to think. Can we just test number of constraints == 0 inside group before filpping?

**Comment by whitequark** [comment]
OK, no problem.

I think that works, yes.

**Comment by whitequark** [comment]
Fixed in 3b55303.
