### ISSUE TITLE
Export 3d Wireframe firstly propose name "untitled.AutoCAD 2007"

### ISSUE THREAD

**Issue by Symbian9** [whitequark/solvespace#119]
In latest nightly when try open export to wireframe dialog it firstly propose name of file as "untitled.AutoCAD 2007", but as look near Save button you will see that it must be STEP File.

When try select DXF directly, it propose normal "untitled.dxf" 

P.S.: Also, propose use in interface definitions "2D" and "3D" instead of "2d" and "3d" that with small letters is not correct.

**Comment by whitequark** [comment]
Not a bug. You have stale settings from back when the extension was determined incorrectly. Simply select DXF or STEP, re-save and this won't happen again.

**Comment by Symbian9** [comment]
@whitequark, Ok, but anyway, try use 2D and 3D instead of 2d and 3d in user interface.
Thanks.

**Comment by whitequark** [comment]
Both spellings are acceptable, like "DC" and "dc" for direct current.
