### ISSUE TITLE
Implement offscreen rendering that is independent of GL implementation

### ISSUE THREAD

**Issue by whitequark** [whitequark/solvespace#125]
This is needed to render reference images for regression testing.

Specifically:
  * Abstract the "draw GL", "add edges" and "get distance" codepaths behind a new class `Canvas`;
  * Add a `Canvas` implementation using [Cairo](http://www.cairographics.org/);
  * Use Cairo for PDF/SVG/etc rendering too? Maybe not.

**Comment by whitequark** [comment]
@Evil-Spirit let's discuss this issue on IRC

**Comment by whitequark** [comment]
@Evil-Spirit For this (for DrawPolygon) we need a tesselator that's independent of GL, i.e. not GLU. Do you have any idea which?

**Comment by Evil-Spirit** [comment]
@whitequark, we can use ear-triangulation approach from triangulate.cpp

**Comment by Evil-Spirit** [comment]
@whitequark, i am going to implement it soon

**Comment by whitequark** [comment]
What are you implementing exactly?

**Comment by Evil-Spirit** [comment]
Quads. Polygons will be the same just with triangulation.

**Comment by Evil-Spirit** [comment]
@whitequark, polygons with native solvespace triangulation working good.

**Comment by whitequark** [comment]
@Evil-Spirit So, how do I turn a polygon into triangles? Can you write some sample code? I've no idea how to use that part.

**Comment by Evil-Spirit** [comment]
@whitequark, look here https://github.com/Evil-Spirit/solvespace/tree/canvas-opengl2

**Comment by Evil-Spirit** [comment]
https://github.com/Evil-Spirit/solvespace/blob/canvas-opengl2/src/rendergl2.cpp#L1607

**Comment by Evil-Spirit** [comment]
new function here https://github.com/Evil-Spirit/solvespace/blob/canvas-opengl2/src/srf/triangulate.cpp#L421

**Comment by whitequark** [comment]
Implemented.
