### ISSUE TITLE
DXF export is unusable in other CADs

### ISSUE THREAD

**Issue by whitequark** [whitequark/solvespace#13]
There are several major issues with DXF export:

 - [x] Circles that are projections of lathe edges are exported as line segments (see #4).
 - [ ] Several lines get overlaid on top of each other.
 - [x] Styles are ignored. In particular, color and thickness are crucial.

This makes it extremely and unnecessarily hard to process a DWG export in librecad to make a shop drawing.

**Comment by whitequark** [comment]
For implementing this I suggest using libdxflib (https://launchpad.net/ubuntu/+source/dxflib/2.5.0.0-2) or libdxfrw (https://github.com/LibreCAD/LibreCAD/tree/master/libraries/libdxfrw). The latter appears to be a fork of the former.

**Comment by Evil-Spirit** [comment]
are you still interesting to improve?

**Comment by whitequark** [comment]
libdxfrw was integrated.
