### ISSUE TITLE
Store constraint label offset in local coordinate system

### ISSUE THREAD

**Issue by Evil-Spirit** [whitequark/solvespace#132]
This will bring good behaviour when we transform sketch - the dimensions have not to jump unwanted way. 
For offset [0,1] label will be centered and 1mm shifted.

![2016-04-18 15 43 22](https://cloud.githubusercontent.com/assets/1980537/14600543/fff42a66-057e-11e6-8947-6476cfe4c452.png)

![2016-04-18 15 58 40](https://cloud.githubusercontent.com/assets/1980537/14600458/7cf6bebc-057e-11e6-9869-156c98303162.png)

**Comment by Evil-Spirit** [comment]
![2016-04-18 15 31 13](https://cloud.githubusercontent.com/assets/1980537/14599730/db67dbba-057a-11e6-845c-3bf1978a99b6.png)

**Comment by Evil-Spirit** [comment]
![2016-04-18 15 43 22](https://cloud.githubusercontent.com/assets/1980537/14600004/642cff4c-057c-11e6-937e-3ff6efbb915e.png)

**Comment by Evil-Spirit** [comment]
![2016-04-18 15 58 40](https://cloud.githubusercontent.com/assets/1980537/14600458/7cf6bebc-057e-11e6-9869-156c98303162.png)

**Comment by whitequark** [comment]
Transform?

**Comment by Evil-Spirit** [comment]
For ex. change dimension value.

**Comment by whitequark** [comment]
Ah yes, this sounds nice. But we need to do something with existing files.

**Comment by Evil-Spirit** [comment]
No problem if we load old, save new approach. If we need, we can save pos in both csys.

**Comment by whitequark** [comment]
That will wait until we have regression tests for savefile format, then.

**Comment by whitequark** [comment]
Migrated to https://github.com/solvespace/solvespace/issues/122.
