### ISSUE TITLE
Why "release-DO-NOT-USE"?

### ISSUE THREAD

**Issue by Symbian9** [whitequark/solvespace#133]
Can you tell why it have this name and why you again separate "libslvs" from "solvespace"?
https://github.com/whitequark/solvespace/releases/tag/release-DO-NOT-USE
Thanks

**Comment by whitequark** [comment]
Because I'm testing the release process. This tag is of no relevance to you.

Re: libslvs, it was always built but it was not uploaded before. Now I just upload all .debs that are built; solvespace does not depend on libslvs.
