### ISSUE TITLE
Use uint64_t for handle id value.

### ISSUE THREAD

**Issue by Evil-Spirit** [whitequark/solvespace#141]
When we are importing big files, there is situation when handle limit reached.
In current implementation we can haldle only 64k of handles(half bits of uint32_t).

We can translate all the handles of saved files into new representation while the loading.

**Comment by whitequark** [comment]
This seems somewhat excessive. I think we are going to fall over in other places (rendering, solver, etc) before we bump into this limit.

**Comment by Evil-Spirit** [comment]
no problem to render and solve only 64k of lines (especially for only H/V/PC like in architectural drawings)

**Comment by Evil-Spirit** [comment]
Of course, in the future, with small fixes of the solver. But since this will be problem if we make new file formats without considering this.

**Comment by whitequark** [comment]
Makes sense.

**Comment by Evil-Spirit** [comment]
inside this improvement we can review the handle generation logic to avoid bit-combine operations and remapping. @jwesthues, any ideas how to avoid remap and don't save the remap lists?

**Comment by whitequark** [comment]
> to avoid bit-combine operations and remapping

Why are you trying to avoid them?

**Comment by Evil-Spirit** [comment]
@whitequark, remapping is something what we have to save into file. We could think and invent new rules for id generation without remapping. Also, we have to introduce 64bit ids and we just can use union representation with 8/16/32 bit fields to make code simplier and cleaner.

**Comment by whitequark** [comment]
Migrated to solvespace/solvespace
