### ISSUE TITLE
Introduce antialiasing for fat lines.

### ISSUE THREAD

**Issue by Evil-Spirit** [whitequark/solvespace#142]
There is only for lines with width <= 3.0.

**Comment by whitequark** [comment]
Before fat-line-aa:
![a](https://cloud.githubusercontent.com/assets/54771/15005454/60e32c8c-11b4-11e6-9f20-1d1b5817750f.png)

After fat-line-aa:
![b](https://cloud.githubusercontent.com/assets/54771/15005455/662f341a-11b4-11e6-9fe1-462d36d9ddae.png)

I don't see any difference.

**Comment by Evil-Spirit** [comment]
Which card/os? Do you have AA on the regular lines?

**Comment by whitequark** [comment]
Intel, Linux

These are regular lines (closed shape to remove red background, but it's AA even with open shape):
![c](https://cloud.githubusercontent.com/assets/54771/15005482/b9c6ebb8-11b4-11e6-8860-adcc3fc29c94.png)

**Comment by Evil-Spirit** [comment]
Which Intel and which linux?

**Comment by whitequark** [comment]
This should be enough: ![2182](https://cloud.githubusercontent.com/assets/54771/15005514/0734d702-11b5-11e6-8516-1950bb58cc1b.png)

The release is Debian testing.

**Comment by Evil-Spirit** [comment]
![2016-05-04 11 05 19](https://cloud.githubusercontent.com/assets/1980537/15005572/2ecd914a-11e8-11e6-87b7-36c7cd47f61f.png)

**Comment by whitequark** [comment]
Well, yes. Gallium is the Mesa software renderer. It implements features of GL_LINES that no one else bothers to

**Comment by Evil-Spirit** [comment]
There is the same lines used for aa, just need to be adjusted.

**Comment by whitequark** [comment]
How about just postponing this until we have GLES rendering? GL_LINES don't work reliably and we should stop using them completely instead.

**Comment by Evil-Spirit** [comment]
OK
