### ISSUE TITLE
Add a display mode without either shaded mesh or occluded lines

### ISSUE THREAD

**Issue by Evil-Spirit** [whitequark/solvespace#143]
In previous versions and now, this button is not only hides shaded mesh, but also shows "hidden" invisible lines, which is not stippled, but just like "wireframe".
I am offering to change this behaviour because now it is impossible to export view to pdf/eps/svg without faces, but with stippled hidden lines (or just edges with hidden lines removed).

**Comment by Evil-Spirit** [comment]
Also, hiding edges causes hiding of outlines, but this is an interesting appearance mode (like in toon-shading).

**Comment by Evil-Spirit** [comment]
Can we include this in 2.1?

**Comment by whitequark** [comment]
I'll look into it

**Comment by whitequark** [comment]
> I am offering to change this behaviour because now it is impossible to export view to pdf/eps/svg without faces, but with stippled hidden lines (or just edges with hidden lines removed).

But you can do that. Turn off view of shaded model, turn on hidden lines.

**Comment by whitequark** [comment]
Just exported this
![2293](https://cloud.githubusercontent.com/assets/54771/15725050/7ab65026-2839-11e6-8ae0-8779ba5b3590.png)

**Comment by Evil-Spirit** [comment]
Turn off hidden, this mode is not supported.

**Comment by whitequark** [comment]
> Turn off hidden, this mode is not supported.

Yeah, we can't do it for either viewport or export. I don't think it's important enough to get into 2.1, so denominating for backport.

**Comment by whitequark** [comment]
@jwesthues Any idea for the UI for this feature? I'm not sure what to do with the proliferation of buttons. Maybe a tri-state one for hidden lines? Shown, stippled, hidden?

**Comment by jwesthues** [comment]
Tri-state seems reasonable to me.

**Comment by whitequark** [comment]
Tri-state button implemented in master.
