### ISSUE TITLE
Make showcase examples for site.

### ISSUE THREAD

**Issue by Evil-Spirit** [whitequark/solvespace#144]

**Comment by whitequark** [comment]
There's already solvespace.com...

**Comment by Evil-Spirit** [comment]
For m-labs.hk page?

**Comment by Evil-Spirit** [comment]
![2016-05-03 13 53 06](https://cloud.githubusercontent.com/assets/1980537/14977606/20cda352-1137-11e6-9934-330cee7bd324.png)

**Comment by whitequark** [comment]
That's internal to m-labs, let's keep it off this issue tracker.

**Comment by Evil-Spirit** [comment]
I've just wanted to make place where I can place it.

**Comment by Evil-Spirit** [comment]
![2016-05-03 13 59 35](https://cloud.githubusercontent.com/assets/1980537/14977644/7eaff5ba-1137-11e6-9da8-0dab170e31af.png)

**Comment by Evil-Spirit** [comment]
I ve already have some files made by me, so, why not to show it, may be it will be interesting.

**Comment by whitequark** [comment]
Sure, you could make a repository, put the files inside and add screenshots to README.md, this way it will be all kept together.

**Comment by Evil-Spirit** [comment]
Too complicated for mess of the files. The good ones we must publish on sites, small amount of the users care about github reops.

**Comment by whitequark** [comment]
That is less messy than manually packaging stuff in zip archives, and a repository with a README.md in the root is as good as a website

**Comment by Evil-Spirit** [comment]
We already have solvespace-testcases, so, we can do it there.

**Comment by Evil-Spirit** [comment]
![2016-04-15 22 48 37](https://cloud.githubusercontent.com/assets/1980537/14977761/b4851638-1138-11e6-8709-c5d20d359222.png)
