### ISSUE TITLE
Don't exhaust file handles on Windows by opening all the fonts

### ISSUE THREAD

**Issue by whitequark** [whitequark/solvespace#145]
This breaks all file operations if the list of fonts is ever read. Instead, close fonts after reading the name and style, and reopen when we actually need to draw with them.

**Comment by whitequark** [comment]
Fixed in 7da5cfb. @Evil-Spirit can you confirm?

**Comment by Evil-Spirit** [comment]
Still broken for me

**Comment by Evil-Spirit** [comment]
This is strange things: When I start researching this bug, it was (with assemblies when we insert text). But now it's gone. And I can't reproduce it again.

**Comment by whitequark** [comment]
Old build?

**Comment by Evil-Spirit** [comment]
Probably. But there is so much repo switches, rebuilds, compilers switches. And it was.
