### ISSUE TITLE
Don't consider arc center-point when calculating tolerances.

### ISSUE THREAD

**Issue by Evil-Spirit** [whitequark/solvespace#146]
This causes problems on the arcs with big radius.
Also, we should not consider construction geometry.
Probably we should mark arc center point as construction.

**Comment by whitequark** [comment]
Can you show an example?

**Comment by Evil-Spirit** [comment]
![2016-05-04 22 03 46](https://cloud.githubusercontent.com/assets/1980537/15020552/48175940-1244-11e6-93b7-76aa8fce9636.png)

**Comment by whitequark** [comment]
Ack.

**Comment by Evil-Spirit** [comment]
Just leave it here for future:
![height_segment_circle](https://cloud.githubusercontent.com/assets/1980537/15066192/0772b632-1389-11e6-9310-28d8c3cf9400.png)
![height_segment_circle_formula3](https://cloud.githubusercontent.com/assets/1980537/15066190/05c2d812-1389-11e6-99ae-ba701db51b1c.png)

**Comment by Evil-Spirit** [comment]
fixed in https://github.com/Evil-Spirit/solvespace/commit/82c35b9809c88bdd66ac3c783320d4d54cbf712b
also, https://github.com/Evil-Spirit/solvespace/commit/4f7bc1ed9d4e10c6610aa060e4b1548ac26b2d5d

**Comment by whitequark** [comment]
Merged.
