### ISSUE TITLE
Figure out what happens with DXF dimensions

### ISSUE THREAD

**Issue by whitequark** [whitequark/solvespace#149]
* Some problem with angle constraints: https://github.com/Evil-Spirit/solvespace/commit/23f2d
 * When importing, labels on dimensions are ignored--should we do that?

**Comment by Evil-Spirit** [comment]
What the problem about labels on dimensions?

**Comment by whitequark** [comment]
see irc

**Comment by Evil-Spirit** [comment]
Some work done in https://github.com/Evil-Spirit/solvespace/tree/dxf-dimensions
see also: https://github.com/Evil-Spirit/libdxfrw/tree/actual-measurement

**Comment by whitequark** [comment]
Fixed in 63abcc379d 11919bf0 ae60187.
