### ISSUE TITLE
Last DXF block imported doesn't get the correct style

### ISSUE THREAD

**Issue by whitequark** [whitequark/solvespace#151]
Reproduce: [blocks.zip](https://github.com/whitequark/solvespace/files/253652/blocks.zip)

**Comment by Evil-Spirit** [comment]
What happens with capital string convertions?

**Comment by Evil-Spirit** [comment]
Sorry, my bad, see comment for commit.
But issue still here.

**Comment by Evil-Spirit** [comment]
@whitequark,
Oh, there is no bug, just need to shedule regenerate all after importing, somehow.
Too see it just press "space" key.

**Comment by whitequark** [comment]
Fixed in 4a8675c12.
