### ISSUE TITLE
Printing

### ISSUE THREAD

**Issue by whitequark** [whitequark/solvespace#157]
Let's have a File → Print... option ourselves, with preview and everything. Simple matter of OS integration.

**Comment by Evil-Spirit** [comment]
http://www.codeproject.com/Articles/8916/Printing-Architecture

**Comment by whitequark** [comment]
And what about print dialogs?

**Comment by Evil-Spirit** [comment]
@whitequark, We can call for standart printing dialog to choose printer, but seems what preview we have do our own. Also, I found info how to print using PostScript itsef, not it's pdf version. We already have PostScript output, so this is not a big problem.
http://stackoverflow.com/questions/2240243/how-do-i-do-print-preview-in-win32-c

**Comment by whitequark** [comment]
That answer says nothing about the dialogs.

**Comment by Evil-Spirit** [comment]
https://msdn.microsoft.com/en-us/library/windows/desktop/ms646829.aspx#print_property

**Comment by whitequark** [comment]
Moved to solvespace/solvespace
