### ISSUE TITLE
More 3D operations: loft, fillet, chamfer

### ISSUE THREAD

**Issue by whitequark** [whitequark/solvespace#16]

**Comment by Evil-Spirit** [comment]
this is very hard with the current NURBS core :( problem is not to build shell, problems is in booleans which cant process any geometry

**Comment by whitequark** [comment]
Yeah, I've learned about this already. How problematic would it be to use a different NURBS core?

**Comment by Evil-Spirit** [comment]
we are trying at the momnet. but we still not found good nurbs library. there is OpenCASCADE - the big and the fat.

**Comment by whitequark** [comment]
Yeah, OpenCASCADE is horrible. I'd really rather avoid it. Have you seen http://www.sintef.no/Projectweb/Geometry-Toolkits/SISL/? It looks exactly like what we need.

**Comment by Evil-Spirit** [comment]
no. no. no. this is shit.

**Comment by whitequark** [comment]
ok. I guess it is worth trying to integrate OCE. hopefully this can be done so that OCE does not infest the rest of codebase.

**Comment by jonnycowboy** [comment]
What about integrating Verb Nurbs instead?  Very power, easy to use, etc...

**Comment by Evil-Spirit** [comment]
as i understand, it have no completed booleans, topo branch probably unstable

**Comment by whitequark** [comment]
We need OpenCASCADE first for this. Looks like there's no other option.

**Comment by agryson** [comment]
bump
Is there any more news on this?
Is it planned for after 3.0?

**Comment by whitequark** [comment]
There are no current plans.

**Comment by rzvc** [comment]
Any updates on this?

If this will be done it will take SolveSpace to a new level. I guess it will also lay down the path for extruded bodies that follow a custom path which will enable a lot more - threads for example.

**Comment by whitequark** [comment]
There are no current plans. Do not expect this to happen.
