### ISSUE TITLE
Three.js model with inbuild PDF renderer

### ISSUE THREAD

**Issue by Symbian9** [whitequark/solvespace#161]
What you think about implementing next library?
* https://github.com/fjenett/threejs-pdf-renderer

**Comment by Evil-Spirit** [comment]
What for?

**Comment by Symbian9** [comment]
For Three.js mesh export template

**Comment by whitequark** [comment]
That wouldn't result in a high-quality technical drawing, just a vector form of a screenshot. I don't think this is any better or more useful than a regular screenshot, so I'm not interested in supporting that feature.
