### ISSUE TITLE
Export interactive PDF (ideas)

### ISSUE THREAD

**Issue by Symbian9** [whitequark/solvespace#162]
<b>In this issue I propose discuss possibility of export PDF with interactive futures</b>:
* show or hide comments or other elements when cursor hover special region on PDF page - http://indesignsecrets.com/showing-and-hiding-objects-in-interactive-pdf.php
* interactive layers switching - http://indesignsecrets.com/changing-layer-visibility-in-an-interactive-pdf.php
* export interactive 3D model directly in PDF (U3D format, PRC format or some other tricks using JS and CSS)
  * https://en.wikipedia.org/wiki/Asymptote_(vector_graphics_language)
  * https://github.com/sumatrapdfreader/sumatrapdf/issues/523
  * https://github.com/mrdoob/three.js/issues/8907
  * https://github.com/humu2009?tab=repositories
  * http://technikhobby.blogspot.com/2013/12/openjscad-goes-mobile.html
* export TrueType Text as interactive "input text form" (for stamps or comments, that can be changed later)
* multipage report with autogenerated specification pages for all parts of assemble
* secure PDF option (export with password)

Interactive futures for technical drawing files can be very usefull for creating different reports and tests.
* http://www.ppsloan.org/publications/iti99.pdf
* http://www.vis.uni-stuttgart.de/~weiskopf/publications/eg2002.pdf
* http://forums.augi.com/showthread.php?155378-Export-3D-Model-to-Interactive-PDF
* https://leadertechinc.com/news/slot-lok-technical-drawings-released/
* http://www.lymnassociates.com/technical-drawing.html
* http://cache.nxp.com/files/microcontrollers/doc/support_info/LFBGAMT3A-INTERACTIVE.pdf
* http://www.chasedoors.com/library_drawings.asp

![Interactive drawing](http://www.lymnassociates.com/images/drawing01.jpg)

<b>Interactive PDF</b> can be good choice for creating interactive reports and there are few tricks and 3rd party tools, that can create some of this futures:
* http://www.techrepublic.com/blog/tr-dojo/create-interactive-pdf-documents-with-scribus/
* http://tex.stackexchange.com/questions/113999/can-i-add-a-blueprint-technical-drawing-to-my-document
* http://onlinelibrary.wiley.com/doi/10.1002/cae.21728/abstract

But I think that it would be usefull add some option for export interactive PDF in SolveSpace.

More ideas coming soon! (this message would be updated)
P.S.: interactive PDF futures very popular in GIS reports ('map', as you know, is one of types of technical drawings):
* http://www.cartography.oregonstate.edu/pdf/2001_Hurni_etal_ica.pdf

**Comment by Evil-Spirit** [comment]
Can you explain why?

**Comment by Evil-Spirit** [comment]
> U3D format

One more "simple", "universal" format (specifiaction consist of 237 pages).

**Comment by Symbian9** [comment]
@Evil-Spirit, there are many reasons and here are some of them:
1) PDF is one of the most popular exchange format for technical drawing reports (after DXF, DWG and few other)
2) PDF readers are one of the application that already preinstalled or firstly instaled on most of users side PC.
3) Some companies not use any CAD software (and not allow install 3rd party CAD), but allow use of PDF documentation.
4) Interactive PDF already used in many university as form of testing papers.
5) Three.js with WebGL can't work on PC with low RAM and GPU, where interactive PDF can work normally.

Also PDF itself is multipage document, that for reports can be greate. Most of well known complex CAD can produce multipage reports and export to PDF. I hope SolveSpace in future would be complex CAD too.

**Comment by Evil-Spirit** [comment]
What's wrong with the current PDF export for technical drawings?

**Comment by Evil-Spirit** [comment]
1)2)3) We already have the PDF export;
4) We don't make the program for tesing of the students.
5) ???? WHAT ????

**Comment by Evil-Spirit** [comment]
So, why you have mentioned "ineractive", "u3d".
You just have to create "make pdf more userful for technical drawings".
There is no need in silence links, just write the features you REALLY need, like

* multipage pdf
* whatever

You just overload us the unrelated information and the some links (i even don't know what I must figure out from looking at)

**Comment by Symbian9** [comment]
@Evil-Spirit, U3D Format is only one of many futures of PDF, but I not say that it "must" be presented in SolveSpace. Think, there can be used some pseudo 3D futures in PDF using JS and CSS (now I'm in search of 3rd party libraries and tricks for that).

For me more interesting is interactive 2D techical drawing reports with interactive comments, switched layers and multipage export with some additional information. For example, resulted PDF can have drawing on 1st page and textual specification in table form on 2nd page or in other order. Think it can be released by adding comments futures for groups inside text browser and few other option for creating specification pages in PDF automaticaly (especially for assembled models). 
![Drawing with specification report](http://konspekta.net/studopediainfo/baza4/2771227915742.files/image145.jpg)

**Comment by whitequark** [comment]
Out of scope for me. It's open-source; if you want it, implement it.

**Comment by whitequark** [comment]
Also, U3D effectively only works with proprietary Acrobat, so that's completely useless.

**Comment by Symbian9** [comment]
@whitequark, I propose 3D implementing using PRC (as alternative to U3D) with next opensource thing
* http://asymptote.sourceforge.net/

**Comment by whitequark** [comment]
That's still limited to Adobe Reader: https://en.wikipedia.org/wiki/PRC_(file_format)#Viewer
