### ISSUE TITLE
Analyze > Measure Perimeter

### ISSUE THREAD

**Issue by Symbian9** [whitequark/solvespace#163]
Is it possible add "Perimeter" analyzer for selected elements (line, curves, arcs and their combination)?
* https://en.wikipedia.org/wiki/Perimeter
* https://www.mathsisfun.com/geometry/perimeter.html

**Comment by whitequark** [comment]
Yep, reasonable.

**Comment by Symbian9** [comment]
There are some examples that show how calculate <b>length of Bezier curve</b>:
* http://steve.hollasch.net/cgindex/curves/cbezarclen.html
* http://www.gamedev.net/topic/313018-calculating-the-length-of-a-bezier-curve/
* https://github.com/HTD/FastBezier
* http://www.tinaja.com/glib/nubzlen1.pdf
* http://www.lemoda.net/maths/bezier-length/index.html

**Comment by whitequark** [comment]
Implemented.
