### ISSUE TITLE
Hide construction (points & lines)

### ISSUE THREAD

**Issue by Symbian9** [whitequark/solvespace#167]
Propose allow hide all "green" elements. For now its possible hide only points (that itself is "constructed" element), but lines and curves (that switched to "CONSTRUCTION") not yet possible hide.
So, think it would be usefull use already presented "Hide points" tab in text window for hide all dots and construction elements in one click and rename this tab to "Hide construction"

**Comment by Evil-Spirit** [comment]
You can assign custom style with ability to change "show these objects on screen". Checking/unchecking this option can emulate this behaviour. I think it will be useful to unlock all the style options even for default styles, so in future you can do it without any custom styles.

**Comment by Symbian9** [comment]
@Evil-Spirit, "CONSTRUCTION" is a type, not a style. I agree with what you say about styles, but anyway propose replace "Hide points" with "Hide construction" button (for hiding all "constructed" elements: points, lines, curves, arcs etc.)

**Comment by whitequark** [comment]
Points are not construction elements though.

**Comment by whitequark** [comment]
> I think it will be useful to unlock all the style options even for default styles, so in future you can do it without any custom styles.

Most of them are never used, which is rather confusing. (Even in the *restricted* list of options, most of them are never used.) That'll have to wait until the new styling system.

**Comment by Evil-Spirit** [comment]
@whitequark, ok, we have to change styling systeem completely.

**Comment by whitequark** [comment]
@jwesthues Opinion on changing the behavior of the "Show/hide points" button to "Show/hide points and construction entities" ?

**Comment by jwesthues** [comment]
Why should construction entities track with points vs. normals or workplanes?

**Comment by whitequark** [comment]
Hm, good point. But I don't like the idea of adding yet another button for construction entities. The text window toolbar is too crowded as it is.

**Comment by whitequark** [comment]
@Symbian9 I agree with @jwesthues, there is no reason to change the behavior of "Show/hide points" button like this.
