### ISSUE TITLE
"Text Window" or "Browser"?

### ISSUE THREAD

**Issue by Symbian9** [whitequark/solvespace#168]
I sew this confuse long time: when you go to "View" menu you will see "Show Text Window", but this window has header "Browser".
I propose rename both this to one - "Property Browser"

**Comment by whitequark** [comment]
@jwesthues? Not sure what the original intent was.

**Comment by jwesthues** [comment]
I started with "text window", but changed (incompletely) to "browser". The rename seems reasonable to me.

**Comment by whitequark** [comment]
Done in b55e096fefd2.

**Comment by Symbian9** [comment]
@whitequark, think, in code there is also an issue that need to rename some , for example <code>MNU_SHOW_TEXT_WND</code>.
I think all strings that include <code>..._TEXT_WND...</code> must be replaced with something that related to header of this window.
