### ISSUE TITLE
Comments are not pasted

### ISSUE THREAD

**Issue by Symbian9** [whitequark/solvespace#169]
Why its impossible paste copied or cutted comment element?

**Comment by whitequark** [comment]
Bug.

**Comment by Evil-Spirit** [comment]
Done. Also, implemented constraint selection while pasting.

**Comment by whitequark** [comment]
> Also, implemented constraint selection while pasting.

What's this for?

**Comment by whitequark** [comment]
Ok this doens't work properly. Try creating a circle and a comment, then copying ONLY circle. The comment will be always copied.

**Comment by whitequark** [comment]
Fixed properly in bb0eef2.
