### ISSUE TITLE
Allow specifying a workplane by a point, line and a normal

### ISSUE THREAD

**Issue by whitequark** [whitequark/solvespace#17]
These come up quite often, and otherwise require adding awkward construction entities with tangent/parallel/perpendicular constraints.

**Comment by whitequark** [comment]
Ah, this wouldn't really work, as some combinations are ambiguous.

**Comment by whitequark** [comment]
Ah, no, that already happens with "point and two line segments", if you put them all on the same line. The sketch just becomes very unstable.

**Comment by whitequark** [comment]
This is useful to start working on a side of an extrusion, especially with arcs; you already have a normal, so you add a point on the arc and draw a tangent line through it.

**Comment by Evil-Spirit** [comment]
I dont see the usecase where we can't use the (already existent) axis of revolution or segment from extrusion of center-point of circle/arc to use it instead of normal. If we will introduce it, we will break file format backward-compatability.

**Comment by whitequark** [comment]
We can't use a line segment and a normal at the same time, and we also cannot use two line segments that don't go through the same point.

**Comment by Evil-Spirit** [comment]
Actually we can use two line segments which is actually don't go through the same point (we take only the directions) and splecify any point for workplane origin (i've just tested it).

**Comment by whitequark** [comment]
Does that already work or does it require code modification? If latter, yes, this is fine by me.

**Comment by Evil-Spirit** [comment]
This already work without any modifications.

**Comment by whitequark** [comment]
Oh, great. Then just the help text needs updating--I'll do it.

**Comment by whitequark** [comment]
Oh haha, I cannot read. It never said that the *lines* need to go through the point.
