### ISSUE TITLE
Icons are not rendered on Windows

### ISSUE THREAD

**Issue by whitequark** [whitequark/solvespace#170]
This is some weird Windows-specific OpenGL problem. They're all loaded correctly (verified in a debugger) but for some reason render as black rectangles.

**Comment by Evil-Spirit** [comment]
Ok, will take a look into this.

**Comment by Evil-Spirit** [comment]
Where can i see it?

**Comment by Evil-Spirit** [comment]
@whitequark, can you provide more information?

**Comment by whitequark** [comment]
This is what I get when building latest master and running on Windows 7 in VirtualBox:
![2241](https://cloud.githubusercontent.com/assets/54771/15430110/62fe7616-1e93-11e6-8b6b-021a880e6764.png)

**Comment by Evil-Spirit** [comment]
@whitequark, I have no such problem (Windows 7 x64)

**Comment by Evil-Spirit** [comment]
Is this problem only for virtual box?

**Comment by whitequark** [comment]
I don't know, I don't have native Windows.

**Comment by whitequark** [comment]
If it's a problem just for VirtualBox then it probably still means misuse of GL that needs to be fixed.

**Comment by Evil-Spirit** [comment]
> glBindTexture(GL_TEXTURE_2D, TEXTURE_DRAW_PIXELS);
You have to call glGenTextures to generate id instead of using TEXTURE_DRAW_PIXELS

**Comment by whitequark** [comment]
But that works elsewhere and also worked before, no?

**Comment by Evil-Spirit** [comment]
I think this was before some specific moment.
the gl spec says
`You must use glGenTextures to generate a set of new texture names.`

**Comment by Evil-Spirit** [comment]
OpenGL always shows good behaviour on the corrupted/wrong input or wrong using of the functions.
When I write my own game projects, such misusing works for a years. Until the some specific moment when memory segments becomes the different or until driver updating.

**Comment by whitequark** [comment]
Yeah you are right. Since this works without Virtualbox let's just fix this when rewriting the rendering code, which should be soon anyway.

**Comment by Evil-Spirit** [comment]
I think we can leave it.

**Comment by whitequark** [comment]
@Evil-Spirit This is still a problem, and using glGenTextures does not fix it. I'll need you to install Windows in VirtualBox and figure out why it fails.

**Comment by Evil-Spirit** [comment]
Have not get success to reproduce this. 
I've tried 
* Under VirtualBox for:
  * WinXP SP3
  * Windows 7 x86 runned on two different laptops (GF650m+Corei7, Intel Atom Z8300)
* Also tried VMWare with no success.
* Without virtualization under:
  * Windows 7 x64
  * Windows 10 x64.

**Comment by whitequark** [comment]
@Evil-Spirit I can still reproduce it. I get `glGetError() == 0x502` messages. Is there some way to get a more verbose explanation on Windows?

**Comment by whitequark** [comment]
@Evil-Spirit I got a GL API trace with apitrace 
[trace.zip](https://github.com/whitequark/solvespace/files/422482/trace.zip). Probably won't help you since apitrace doesn't record errors, only GL calls. But anyway, this is what it shows:
![2477](https://cloud.githubusercontent.com/assets/54771/17735107/18e5f4be-6470-11e6-8bfb-082eb21b4a13.png)

How do I get a more useful error out of Windows?

**Comment by whitequark** [comment]
@Evil-Spirit Also, did you enable any acceleration in vbox? I am running without either 3d or 2d acceleration enabled.

**Comment by Evil-Spirit** [comment]
@whitequark, I have tested both with and without acceleration. There all good parameters passed, but could you try to pass 16x16 instead of 24x24 for width and height? May be OpenGL excepted POT texture size?

**Comment by whitequark** [comment]
@Evil-Spirit Bingo! What sort of fucking braindead restriction is that.

**Comment by whitequark** [comment]
This is apparently how GL1.1 works. https://www.opengl.org/registry/specs/ARB/texture_non_power_of_two.txt

**Comment by whitequark** [comment]
Fixed in master.
