### ISSUE TITLE
SLVZ - compressed SLVS file format

### ISSUE THREAD

**Issue by Symbian9** [whitequark/solvespace#174]
What you think about possibility add support for compressed SLVS format using ZIP algorithm? (similar as SVGZ that is compressed SVG). 
While SLVS is simple text format any complex model will have file with big size.

Futures:
* smaller file size for store and exchange
* multiparts assemble can be stored as single file (inside SLVZ archive all parts of assemble would be stored as normal SLVS files)
* additional resources can be stored with model (background image, fonts)

**Comment by whitequark** [comment]
Yes, that's already planned, though not mentioned on the bug tracker. I'll elaborate my solution later, in another issue.
