### ISSUE TITLE
libui - tiny crossplatform GUI library on pure C

### ISSUE THREAD

**Issue by Symbian9** [whitequark/solvespace#179]
Please, take a look on this GUI library; maybe it would be usefull for SolveSpace.
https://news.ycombinator.com/item?id=11735393

**Comment by whitequark** [comment]
No.

**Comment by whitequark** [comment]
Also, please stop wasting my time with suggestions on writing code. They are never useful. If you want a feature, suggest it, and we are well able to decide how to implement it without you spending a few minutes to Google something completely irrelevant.
