### ISSUE TITLE
SolveSpace use style of latest saved file as factory defaults settings

### ISSUE THREAD

**Issue by Symbian9** [whitequark/solvespace#183]
Now when change size of text inside standart styles (that have <code>#def</code> in name) and after that try use "load factory defaults" command text size still look as defined by user and NOT as it must be (default text size in SolveSpace is 11.5 px).

**Comment by Symbian9** [comment]
Additional info to reproduce:
* run SolveSpace
* change text height inside <code>s006-#def-constraint</code> style to 60 px (for example)
* save this file
* close SolveSpace
* reopen SolveSpace
* default text for comments now look as 60 px
* change it again to 11.5 px
* add any comment text
* try "load factory defaults"

Think, SolveSpace least saved style as factory defaults

UPD: <b>this bug also work for colors and other style parametres too</b>

**Comment by Evil-Spirit** [comment]
Ok ill do it

**Comment by Evil-Spirit** [comment]
Fixed

**Comment by whitequark** [comment]
Fixed in 73d82a6.
