### ISSUE TITLE
Signed distance, angle, etc constraints

### ISSUE THREAD

**Issue by whitequark** [whitequark/solvespace#195]
This is a prerequisite for #194; without this sketches can wildly change orientation when changing just constraint values.

**Comment by Evil-Spirit** [comment]
I've found what this can be called "preserving chirality"
https://en.wikipedia.org/wiki/Chirality

we can do it for:
* PROJ_PT_DISTANCE
* PT_LINE_DISTANCE
* PT_PLANE_DISTANCE
* PT_FACE_DISTANCE
* SYMMETRIC
* SYMMETRIC_HORIZ
* SYMMETRIC_VERT
* SYMMETRIC_LINE
* HORIZONTAL
* VERTICAL
* PERPENDICULAR
* ANGLE
* ARC_LINE_TANGENT
* CUBIC_LINE_TANGENT
* CURVE_CURVE_TANGENT
* PARALLEL

**Comment by Evil-Spirit** [comment]
For implementing this we should introduce for each constraint:
* "option" (pos/neg, parallel/antiparallel)
* "preserve chirality" (ability to trun off "sign" considering and turn back to the old behaviour)

**Comment by whitequark** [comment]
This will not be done with old file format anyway.

**Comment by Evil-Spirit** [comment]
@whitequark, ofc

**Comment by whitequark** [comment]
Migrated to solvespace/solvespace
