### ISSUE TITLE
Character table for text input field

### ISSUE THREAD

**Issue by Symbian9** [whitequark/solvespace#203]
Is it possible add simple character table preview for inserting special characters without external application?
Something like "on-screen keyboard" specially for solvespace inbuilt font with preview

**Comment by whitequark** [comment]
No. You are asking for an input method. This is not something that SolveSpace is responsible for; rather, configure your OS to provide this functionality. The builtin font does not deviate from Unicode so it does not give any additional benefit to show characters from it as preview.
