### ISSUE TITLE
Problem with comment pasting

### ISSUE THREAD

**Issue by Symbian9** [whitequark/solvespace#205]
In latest release 2.1 need fix thing with right button contextual menu.

REPRODUCING
* run SolveSpace
* create only one comment
* cut this comment
* click on right mouse button - nothing, its not show me contextual menu and only possible way paste cutted comment is by CTRL+V combination.

With other object (not "Comment") right button work well.

**Comment by whitequark** [comment]
Fixed in 85cd44d.
