### ISSUE TITLE
Bizarre results with transparency

### ISSUE THREAD

**Issue by whitequark** [whitequark/solvespace#209]
[top.zip](https://github.com/whitequark/solvespace/files/328827/top.zip)
![2336](https://cloud.githubusercontent.com/assets/54771/16285076/d7abf61a-38c3-11e6-9eaf-7a0d818dce43.png)

**Comment by whitequark** [comment]
This needs to be handled in the new renderer, I think.

**Comment by Evil-Spirit** [comment]
@whitequark, it is the common problem in computer graphics. There is no simple solution in general;
the problem solutions you can see here https://habrahabr.ru/post/224003/
I don't think what we need to fight it now.

**Comment by whitequark** [comment]
OK I see.

**Comment by whitequark** [comment]
@Evil-Spirit  this is how it looks in new renderer:
![2716](https://cloud.githubusercontent.com/assets/54771/20871404/714b4a50-ba8d-11e6-8a68-f1c15ee7cbe7.png)
which... is even weirder. I think this is because of depth buffer?

**Comment by whitequark** [comment]
from the other side:
![2717](https://cloud.githubusercontent.com/assets/54771/20871424/a47c719c-ba8d-11e6-848a-3bf9b2ed7e5c.png)

I feel maybe there's an easy fix somewhere. Are we drawing all the faces we should draw?

**Comment by Evil-Spirit** [comment]
@whitequark, Sorting of triangles inside mesh by transparency should help (triangles with transparency should be the last)

**Comment by whitequark** [comment]
@Evil-Spirit I think we can easily do that with the new renderer, because we only sort once, not every frame.

**Comment by whitequark** [comment]
@Evil-Spirit I fixed it in master.
