### ISSUE TITLE
Allow using pi in expressions

### ISSUE THREAD

**Issue by whitequark** [whitequark/solvespace#21]

**Comment by Evil-Spirit** [comment]
Please, provide more information. Do you want to use PI while entering value of the constraint?

**Comment by whitequark** [comment]
I don't remember what I needed this for... anyway, this is not high-priority

**Comment by whitequark** [comment]
But yes, the idea was that one could use pi while entering the value of a constraint. Maybe I tried to enter a diameter based on circle length or something.

**Comment by Evil-Spirit** [comment]
better to have circle-length and arc-length constraint i think

**Comment by whitequark** [comment]
I think I was designing a cylinder involute. But either way, it's not important, one can just use a calculator

**Comment by whitequark** [comment]
Fixed in 3952cd3.
