### ISSUE TITLE
Also show point-line distance projected onto workplane in the text window

### ISSUE THREAD

**Issue by whitequark** [whitequark/solvespace#212]
Otherwise it gets pretty confusing, as the line that gets selected is not necessarily the one in current workplane. And it's convenient in general.

**Comment by Evil-Spirit** [comment]
You mean something like this?
![2016-07-12 22 03 47](https://cloud.githubusercontent.com/assets/1980537/16774150/9e410a28-487c-11e6-93ca-5657e9c0c81c.png)

**Comment by whitequark** [comment]
No. I mean add it in the text window, just like it currently shows distances between points, etc

**Comment by Evil-Spirit** [comment]
Ok. But what we should to do with such visualization?

**Comment by whitequark** [comment]
I think it's not a big deal for now.

**Comment by Evil-Spirit** [comment]
You mean add "pt-ln distance projected = ..."?

**Comment by whitequark** [comment]
Yes.

**Comment by whitequark** [comment]
Fixed in master.
