### ISSUE TITLE
Add "1:1" mode displaying geometry with screen size as actual size

### ISSUE THREAD

**Issue by whitequark** [whitequark/solvespace#214]
Needs a platform support function to get DPI.

**Comment by Symbian9** [comment]
It would be cool!

Try look inside OOMapper settings dialog how its calculate display DPI
* http://github.com/openorienteering/mapper

Related:
* https://github.com/whitequark/solvespace/issues/48

**Comment by whitequark** [comment]
That's completely irrelevant. I am not using Qt.

**Comment by whitequark** [comment]
Implemented.
