### ISSUE TITLE
Arcs not exported properly into DXF

### ISSUE THREAD

**Issue by whitequark** [whitequark/solvespace#218]
Arcs should be exported into DXF as arcs. In this case there is no occlusion and the view is exactly parallel to the workplane, yet somehow they end up as pwl:
[problem.zip](https://github.com/whitequark/solvespace/files/339766/problem.zip)

**Comment by Evil-Spirit** [comment]
I don't have such problem.

**Comment by Evil-Spirit** [comment]
![2016-07-01 00 22 35](https://cloud.githubusercontent.com/assets/1980537/16499384/1734a700-3f22-11e6-833d-95a326a17b9f.png)

**Comment by whitequark** [comment]
... Oh. I had a "Export curves as piecewise linear" checkbox set for some reason and didn't notice it. We really need to get rid of these global settings.
