### ISSUE TITLE
solvespace as command line tools

### ISSUE THREAD

**Issue by ryannining** [whitequark/solvespace#220]
Question.

Since its possible to read parameter from external text file.

Is it possible to make solvespace as command line tools ? inputing svls file and outputing stl, png preview or svg for laser cut.
Because if possible it will be great to have web based parametric part generator, user can enter parameter of the part will be generated and press update then download. It will be nice openscad replacement, because user can create content using real GUI Solvespace then share on web. Openscad require user to code instead of doing UI CAD.

Thanks.

**Comment by whitequark** [comment]
No, not currently.

**Comment by ryannining** [comment]
ok, i have try to hack the solvespace to compile and run on cheap vps...

![Compile, run command line, download the STL, preview in meshlab]
(http://i.imgur.com/dEp4bHf.png)

**Comment by ryannining** [comment]
now trying make simple web GUI

**Comment by whitequark** [comment]
Implemented in master branch.
