### ISSUE TITLE
Can't install on ubuntu 16.04 LTS

### ISSUE THREAD

**Issue by Vincent14** [whitequark/solvespace#222]
According to README.md file, I've tried to install the dependencies, without success:

$ sudo apt-get install libpng-dev libjson-c-dev libfreetype6-dev                 libfontconfig1-dev libgtkmm-2.4-dev libpangomm-1.4-dev                 libgl-dev libglu-dev libglew-dev cmake
[sudo] Mot de passe de vincent : 
Lecture des listes de paquets... Fait
Construction de l'arbre des dépendances       
Lecture des informations d'état... Fait
Note : sélection de « libpng12-dev » au lieu de « libpng-dev »
Note : sélection de « libgl1-mesa-dev » au lieu de « libgl-dev »
Note : sélection de « libglu1-mesa-dev » au lieu de « libglu-dev »
libfontconfig1-dev is already the newest version (2.11.94-0ubuntu1).
libfontconfig1-dev passé en « installé manuellement ».
libfreetype6-dev is already the newest version (2.6.1-0.1ubuntu2).
libfreetype6-dev passé en « installé manuellement ».
libgl1-mesa-dev is already the newest version (11.2.0-1ubuntu2).
libgl1-mesa-dev passé en « installé manuellement ».
libglu1-mesa-dev is already the newest version (9.0.0-2.1).
libglu1-mesa-dev passé en « installé manuellement ».
libpng12-dev is already the newest version (1.2.54-1ubuntu1).
libpng12-dev passé en « installé manuellement ».
Vous pouvez lancer « apt-get -f install » pour corriger ces problèmes :
Les paquets suivants contiennent des dépendances non satisfaites :
 cmake : Dépend: cmake-data (= 3.5.1-1ubuntu2) mais ne sera pas installé
 libgtkmm-2.4-dev : Dépend: libglibmm-2.4-dev (>= 2.27.93) mais ne sera pas installé
                    Dépend: libatkmm-1.6-dev (>= 2.22.2) mais ne sera pas installé
 libpangomm-1.4-dev : Dépend: libcairomm-1.0-dev (>= 1.12.0) mais ne sera pas installé
                      Dépend: libglibmm-2.4-dev (>= 2.46.1) mais ne sera pas installé
 solvespace : Dépend: libatkmm-1.6-1 (>= 2.22.1) mais il n'est pas installable
              Dépend: libcairomm-1.0-1 (>= 1.6.4) mais il n'est pas installable
              Dépend: libglew1.10 (>= 1.10.0) mais il n'est pas installable
              Dépend: libglibmm-2.4-1c2a (>= 2.36.2) mais il n'est pas installable
              Dépend: libgtkmm-2.4-1c2a (>= 1:2.24.0) mais il n'est pas installable
              Dépend: libpangomm-1.4-1 (>= 2.27.1) mais il n'est pas installable
              Dépend: libsigc++-2.0-0c2a (>= 2.0.2) mais il n'est pas installable
E: Dépendances non satisfaites. Essayez « apt-get -f install » sans paquet
(ou indiquez une solution).

I wanted to install debs files from https://github.com/solvespace/solvespace/releases in version 2.1, but dpkg -i return dependencies errors.

**Comment by whitequark** [comment]
I've just tried running the command you're using on a fresh Ubuntu 16.04 install, and there are no dependency problems:
```
$ sudo apt-get install libpng-dev libjson-c-dev libfreetype6-dev libfontconfig1-dev libgtkmm-2.4-dev libpangomm-1.4-dev libgl-dev libglu-dev libglew-dev cmake
[sudo] password for user: 
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Note, selecting 'libpng12-dev' instead of 'libpng-dev'
Note, selecting 'libgl1-mesa-dev' instead of 'libgl-dev'
Note, selecting 'libglu1-mesa-dev' instead of 'libglu-dev'
The following additional packages will be installed:
  autotools-dev cmake-data debhelper dh-strip-nondeterminism gir1.2-gtk-2.0
  libatk1.0-dev libatkmm-1.6-dev libcairo-script-interpreter2 libcairo2-dev
  libcairomm-1.0-dev libdrm-amdgpu1 libdrm-dev libdrm-intel1 libdrm-nouveau2
  libdrm-radeon1 libdrm2 libexpat1 libexpat1-dev
  libfile-stripnondeterminism-perl libgdk-pixbuf2.0-dev libglib2.0-0
  libglib2.0-bin libglib2.0-dev libglibmm-2.4-dev libgtk2.0-dev
  libgtkmm-2.4-1v5 libharfbuzz-dev libharfbuzz-gobject0 libice-dev libjsoncpp1
  libmail-sendmail-perl libpango1.0-dev libpcre3-dev libpcre32-3 libpcrecpp0v5
  libpixman-1-dev libpthread-stubs0-dev libsigc++-2.0-dev libsm-dev
  libsys-hostname-long-perl libx11-dev libx11-doc libx11-xcb-dev libxau-dev
  libxcb-dri2-0-dev libxcb-dri3-dev libxcb-glx0-dev libxcb-present-dev
  libxcb-randr0-dev libxcb-render0-dev libxcb-shape0-dev libxcb-shm0-dev
  libxcb-sync-dev libxcb-xfixes0-dev libxcb1-dev libxcomposite-dev
  libxcursor-dev libxdamage-dev libxdmcp-dev libxext-dev libxfixes-dev
  libxft-dev libxi-dev libxinerama-dev libxml2-utils libxrandr-dev
  libxrender-dev libxshmfence-dev libxxf86vm-dev mesa-common-dev po-debconf
  x11proto-composite-dev x11proto-core-dev x11proto-damage-dev
  x11proto-dri2-dev x11proto-fixes-dev x11proto-gl-dev x11proto-input-dev
  x11proto-kb-dev x11proto-randr-dev x11proto-render-dev x11proto-xext-dev
  x11proto-xf86vidmode-dev x11proto-xinerama-dev xorg-sgml-doctools xtrans-dev
  zlib1g-dev
Suggested packages:
  codeblocks eclipse ninja-build dh-make libatkmm-1.6-doc libcairo2-doc
  libcairomm-1.0-doc libglib2.0-doc libglibmm-2.4-doc libgtkmm-3.0-dev
  libgtk2.0-doc libgtkmm-2.4-doc libice-doc libpango1.0-doc libsigc++-2.0-doc
  libsm-doc libxcb-doc libxext-doc libmail-box-perl
The following NEW packages will be installed:
  autotools-dev cmake cmake-data debhelper dh-strip-nondeterminism
  gir1.2-gtk-2.0 libatk1.0-dev libatkmm-1.6-dev libcairo-script-interpreter2
  libcairo2-dev libcairomm-1.0-dev libdrm-dev libexpat1-dev
  libfile-stripnondeterminism-perl libfontconfig1-dev libfreetype6-dev
  libgdk-pixbuf2.0-dev libgl1-mesa-dev libglew-dev libglib2.0-dev
  libglibmm-2.4-dev libglu1-mesa-dev libgtk2.0-dev libgtkmm-2.4-1v5
  libgtkmm-2.4-dev libharfbuzz-dev libharfbuzz-gobject0 libice-dev
  libjson-c-dev libjsoncpp1 libmail-sendmail-perl libpango1.0-dev
  libpangomm-1.4-dev libpcre3-dev libpcre32-3 libpcrecpp0v5 libpixman-1-dev
  libpng12-dev libpthread-stubs0-dev libsigc++-2.0-dev libsm-dev
  libsys-hostname-long-perl libx11-dev libx11-doc libx11-xcb-dev libxau-dev
  libxcb-dri2-0-dev libxcb-dri3-dev libxcb-glx0-dev libxcb-present-dev
  libxcb-randr0-dev libxcb-render0-dev libxcb-shape0-dev libxcb-shm0-dev
  libxcb-sync-dev libxcb-xfixes0-dev libxcb1-dev libxcomposite-dev
  libxcursor-dev libxdamage-dev libxdmcp-dev libxext-dev libxfixes-dev
  libxft-dev libxi-dev libxinerama-dev libxml2-utils libxrandr-dev
  libxrender-dev libxshmfence-dev libxxf86vm-dev mesa-common-dev po-debconf
  x11proto-composite-dev x11proto-core-dev x11proto-damage-dev
  x11proto-dri2-dev x11proto-fixes-dev x11proto-gl-dev x11proto-input-dev
  x11proto-kb-dev x11proto-randr-dev x11proto-render-dev x11proto-xext-dev
  x11proto-xf86vidmode-dev x11proto-xinerama-dev xorg-sgml-doctools xtrans-dev
  zlib1g-dev
The following packages will be upgraded:
  libdrm-amdgpu1 libdrm-intel1 libdrm-nouveau2 libdrm-radeon1 libdrm2
  libexpat1 libglib2.0-0 libglib2.0-bin
8 upgraded, 89 newly installed, 0 to remove and 324 not upgraded.
Need to get 20.4 MB/21.7 MB of archives.
After this operation, 122 MB of additional disk space will be used.
Do you want to continue? [Y/n]
```

It would seem that there is some issue with your system. Unfortunately, not only I don't know what it is, but I'm not even sure what other information you could provide to shed light on that, so it seems I'm unable to help you.

Consider asking about your dependency issue in the Ubuntu support channels (AskUbuntu, #ubuntu on irc.freenode.net, etc).

I'm quite aware of the limited usefulness of the published .debs. Unfortunately, there is no easy solution for that, for now.
