### ISSUE TITLE
Keep selected objects while change view

### ISSUE THREAD

**Issue by Symbian9** [whitequark/solvespace#227]
Now if select some object/element (point, line, etc.) and then use change view all them automatically unselect 
For example, this issue presented after use:
* "Align View to Workplane"
* "Nearest Ortho View"
* "Nearest Isometric View"
* "Center View At Point"

But when other option from "View" submenu used all selected objects keep selected after changing view
* "Zoom In"
* "Zoom Out"
* "Zoom To Fit"
* "Use Perspective"

So, fix SolveSpace for keep selected objects after any view changing.

**Comment by whitequark** [comment]
> "Nearest Ortho View"
> "Nearest Isometric View"

I just checked and these keep selection.

> "Align View to Workplane"
> "Center View At Point"

These require a selection to proceed. In fact, if you select anything except a workplane (for the 1st case) or a point (for the 2nd case), it will cause an error. And it is a common pattern in SolveSpace that commands requiring selection to proceed clear that selection afterwards.

So, closing as invalid.

**Comment by Evil-Spirit** [comment]
fixed anyway.

**Comment by whitequark** [comment]
@Evil-Spirit Oh, good catch, thanks!

**Comment by Symbian9** [comment]
Thank You both!

**Comment by Symbian9** [comment]
Anyway, "Align View to Workplane" no need selection, because its automatically aligned to active (latest in group list) or nearest workplane

**Comment by whitequark** [comment]
Fixed in master and 2.x.
