### ISSUE TITLE
SolveSpace 2.1 (typo issues)

### ISSUE THREAD

**Issue by Symbian9** [whitequark/solvespace#228]
Here are small issues in UI typography. Please, fix them:
* "... 2d ..." -> "... <b>2D</b> ..."
* "... 3d ..." -> "... <b>3D</b> ..."
* "Zoom To Fit" -> "Zoom <b>to</b> Fit"
* "Center View At Point" -> "Center View <b>at</b> Point"
* "Sketch In 3d" -> "Sketch <b>in 3D</b>"
* "Anywhere In 3d" -> "Anywhere <b>in 3D</b>"
* "New group in 3d (Shift+3)" -> "New group in <b>3D</b> (Shift+3)"
* "Lathe" -> "<b>Solid of revolution / Lathe</b>" (if group type is "union" - its "Solid of revolution", if group type "difference" - its "Lathe")
    * https://en.wikipedia.org/wiki/Solid_of_revolution
    * https://en.wikipedia.org/wiki/Lathe

Maybe, there are also another, but now I not remember.

**Comment by whitequark** [comment]
Not typos.

**Comment by Symbian9** [comment]
Then, why there are different "in/In": "Sketch In 3d" and "New group in 3d (Shift+3)"?

Anyway, UI must look as software standart, so "2d/3d" must be replaced "2D/3D"

**Comment by Evil-Spirit** [comment]
@Symbian9, there is no software standarts.
