### ISSUE TITLE
Crash in DoProjectedPoint

### ISSUE THREAD

**Issue by whitequark** [whitequark/solvespace#232]
To reproduce:
- switch to Free in 3D
- draw line and point
- add a distance constraint

Broken in https://github.com/whitequark/solvespace/commit/6e17780e01d89878172fe1eb36070361bbcba801

**Comment by whitequark** [comment]
I've commented this code for now, so uncomment it when testing.

**Comment by whitequark** [comment]
@Evil-Spirit Please look into this.

**Comment by Evil-Spirit** [comment]
@whitequark, ok

**Comment by Evil-Spirit** [comment]
@whitequark, just performed test. The constraints visualization should be reconsidered in the future to prform drawing all the parts of the same dimension always in one plane.

**Comment by whitequark** [comment]
Yeah, there are a few odd cases in visualization that are visually unpelasant.

**Comment by whitequark** [comment]
This really isn't any better... should we just disable this?
![2607](https://cloud.githubusercontent.com/assets/54771/19220225/de6dbf34-8e17-11e6-9514-39951f57f81c.png)

**Comment by whitequark** [comment]
Actually, as far as I can see, rendering-wise your patch doesn't change *anything*. Is this right?

**Comment by whitequark** [comment]
Ok I see the description of the original commit (in 6e17780e0). Actually, what's the problem with drawing it like 
![2608](https://cloud.githubusercontent.com/assets/54771/19220271/33dfb106-8e19-11e6-9c9f-88a13a1acc4f.png)
for the free in 3D case?

**Comment by Evil-Spirit** [comment]
@whitequark,
implemented here https://github.com/Evil-Spirit/solvespace-master/commits/issue-wq-232
+some bug fixes

**Comment by whitequark** [comment]
Merged
