### ISSUE TITLE
Keep "Property browser" as top window in WINE

### ISSUE THREAD

**Issue by Symbian9** [whitequark/solvespace#234]
As I know, Linux and OS X users often use Win32 build of SolveSpace under WINE.

Issue here is that any floated subwindows not have flag "TOP POSITION" and go to background if select main window.

Please, fix it to allow SolveSpace automatically set top window position of its subwindows.

**Comment by whitequark** [comment]
No. Use the native packages instead. There's a reason those exist.

**Comment by Symbian9** [comment]
But, where get SolveSpace 2.1 for 32bit???

**Comment by whitequark** [comment]
For now? Simply build it from source. The instructions are in README, and it is not hard.
