### ISSUE TITLE
Points not on line 2d

### ISSUE THREAD

**Issue by Leichtbier** [whitequark/solvespace#235]
I've imported a dxf file and not all points aren't  rendered at their exact positions.  Particularly the points on former arc segments. 

![points_not_on_line](https://cloud.githubusercontent.com/assets/20740167/17457216/5f469ad4-5bf2-11e6-81f2-941576775800.png)

The imported file:
[bottom.zip](https://github.com/whitequark/solvespace/files/405047/bottom.zip)

Best regards 

Leichtbier

**Comment by whitequark** [comment]
Not a bug. The DXF file contains a cubic bezier curve, which was imported exactly. These are its control points:
![2442](https://cloud.githubusercontent.com/assets/54771/17457292/8f341bb8-5be3-11e6-868e-b27354f7bb04.png)

Decrease chord tolerance to make them look more like curves.
