### ISSUE TITLE
default filename at export

### ISSUE THREAD

**Issue by tgirod** [whitequark/solvespace#241]
In version 2.1, exported files are called `untitled.EXT` by default. I think it would be more convenient to call them after the name of the exported file - which is the behaviour of most applications.

That's a very low hanging fruit, I might be able to do it if you folks are ok and I find the time.

**Comment by whitequark** [comment]
This is actually deliberate. Especially when exporting 2d views, often you want to export more than one, and this "untitled" suggests that the name should be changed to something descriptive.

**Comment by tgirod** [comment]
IMHO it is better not to make any assumptions about how the user uses a function, and follow a widely accepted, unsurprising behaviour.

If we are to make assumptions, I think it makes sense to have the exported filename as a prefix to all the 2D views exported. So the export behaviour could be altered to `EXPORTED.EXT`, with `EXPORTED` selected, so the user can suppress the filename or quickly add something after.

**Comment by whitequark** [comment]
> So the export behaviour could be altered to EXPORTED.EXT, with EXPORTED selected, so the user can suppress the filename or quickly add something after.

Makes sense. I'll implement this.

**Comment by whitequark** [comment]
Fixed in master.
