### ISSUE TITLE
Issues during linking

### ISSUE THREAD

**Issue by baryluk** [whitequark/solvespace#30]
I think few libraries are not linked correctly when linking solvespace or CDemo, I edited manually link.txt files, and added -lstdc++ -lm -lX11 and everything linked finally.

**Comment by whitequark** [comment]
Platform?

**Comment by baryluk** [comment]
Debian testing/unstable.

**Comment by whitequark** [comment]
Odd. Are you building the for-upstream branch? Can you post the full configure and build log?

**Comment by whitequark** [comment]
@baryluk  Ping?

**Comment by whitequark** [comment]
Nevermind, reproduced and fixed
