### ISSUE TITLE
Make daily builds as PortableLinuxApp (32bit and 64bit)

### ISSUE THREAD

**Issue by Symbian9** [whitequark/solvespace#34]
Think SolveSpace must be "portable" like "dmg" or "exe", without any dependency.
There is a way -  "PortableLinuxApps" are apps that run on most 32-bit or 64- bit Linux-based operating systems, such as Ubuntu, Fedora, debian and derivatives. 
They are bundled into self-containing files: 1 app = 1 file (*.run, ELF).
http://portablelinuxapps.org/

Please, add this as part of daily(nightly) builds for resolve dependency issues for Linux users!

P.S.: I use TahrPup - PuppyLinux (~200Mb only!), based on Trusty 14.04. In PuppyLinux they have "SFS package" for portability apps.
Now previos build "solvespace_2.1_v10~trusty_i386" added - http://distro.ibiblio.org/puppylinux/pet_packages-tahr/solvespace-2.1.sfs.

**Comment by whitequark** [comment]
No, that's a terrible solution. The proper way to handle this is to use SUSE's [Open Build Service](https://build.opensuse.org/) and build native packages for all interesting distributions. I don't have time for that, though.

**Comment by Symbian9** [comment]
But, is it a way make daily/nightly builds in style like Blender3D, when all shared libs included and it run from unzipped folder?
For example, how install this for offline PC with "LinuxMint 15" ?

**Comment by whitequark** [comment]
Use [apt-offline](http://apt-offline.alioth.debian.org/) for installing anything on offline PCs.

**Comment by Symbian9** [comment]
apt-offline need registering... I only wont "every day fresh" version of SolveSpace like unzip and run, without any carry of dependency, but have not win or mac.

Offtopic: Maybe its real make port for KolibryOS (assembler os)?

**Comment by whitequark** [comment]
You have the source. You are free to compile SolveSpace however you want.

And no.
