### ISSUE TITLE
SolveSpace port for KolibryOS

### ISSUE THREAD

**Issue by Symbian9** [whitequark/solvespace#35]
en.wikipedia.org/wiki/KolibriOS
Now its have support for:

- "C/C++" programming
1. http://m.habrahabr.ru/company/kolibrios/blog/229231/
2. http://wiki.kolibrios.org/wiki/C/C%2B%2B_programming

- "MESA" port
http://board.kolibrios.org/viewtopic.php?f=24&t=1678

- "TinyGL" port 
1. http://www.iadn.narod.ru/
2. http://3d.morphos-team.net/

What need alse to compile SolveSpace for it?

**Comment by whitequark** [comment]
I don't care. KolibriOS is worthless.
