### ISSUE TITLE
AC3D (.ac) exporter

### ISSUE THREAD

**Issue by Symbian9** [whitequark/solvespace#36]
Please, add AC3D format for export that will work ou tof the box. 

https://en.wikipedia.org/wiki/AC3D

Here is a python addon for Blender (with comments in passing code)
https://github.com/majic79/Blender-AC3D

And here is few convertors with opensource writen on C / C++
http://texel3d.free.fr/projets/ani2pov/
http://www.inivis.com/forum/showthread.php?t=1923
http://www.programdoc.com/312_1551_1.htm

**Comment by whitequark** [comment]
I am not interested in supporting this format.

**Comment by Symbian9** [comment]
So, maybe you have plane how implement some simple scripting for easy way make plug-in for SolveSpace. It would be greate add some possibility to easy way add parser rules without need now C++ and recompil your program if need only add this future. What You think?

**Comment by whitequark** [comment]
Not happening any time soon.
