### ISSUE TITLE
Lathe group edges/faces are not selectable

### ISSUE THREAD

**Issue by whitequark** [whitequark/solvespace#4]
If you extrude a group, you can select a face and create a workplane on it. If you however lathe a group (sample data: http://rghost.net/75qGtXsJF), you cannot select any edges or faces. At the very least, edges and flat faces should be selectable.

**Comment by whitequark** [comment]
Why does this happen? I'm not sure. It looks like SBezier::IsCircle doesn't return true for lathe'd edges.

**Comment by Evil-Spirit** [comment]
refresh sample please

**Comment by whitequark** [comment]
E.g. this: http://rghost.net/6rJsQrQns

The reason is just that the 3D entities such as faces and edges are created explicitly for extrude groups. But, this does not happen at all for lathe groups. See groupmesh.cpp:210

**Comment by Evil-Spirit** [comment]
yes, lathe is empty, need to insert some code here https://github.com/whitequark/solvespace/blob/for-upstream/src/group.cpp#L398
i think need to build face only for sketch lines what are perpendicular to the revolution axis. 
is there any other cases?

**Comment by whitequark** [comment]
Yeah, face entities should only be built for faces that lie entirely in a plane.

**Comment by whitequark** [comment]
Fixed.
