### ISSUE TITLE
Renaming imported files

### ISSUE THREAD

**Issue by tgirod** [whitequark/solvespace#44]
Moving/renaming a file that is used somewhere else as an import tend to cause troubles for the importing file.

In the properties, it would be great to be able to edit the "import geometry from file" parameter.

EDIT: fortunately I could solve my problem by editing the files by hand - blessed be human readable data formats !

**Comment by whitequark** [comment]
Yeah, I think we should add a dialog box prompting the user to locate the file.

**Comment by whitequark** [comment]
Done
