### ISSUE TITLE
Dynamic "Scale bar" constrain

### ISSUE THREAD

**Issue by Symbian9** [whitequark/solvespace#48]
Please, add dynamic "Scale  bar" constraint, that can be like "Comment", and can printed/exported with "Export 2D"(with option to choose units: meters, cm, km or other)
Here are example about what I told:
http://4.bp.blogspot.com/-oims9OoG-0Y/UCwGfHLM2uI/AAAAAAAABAo/tQjMcmxOfeY/s1600/dynamic_viewport_scale_bar.png
http://help.autodesk.com/cloudhelp/2016/ENU/MAP3D-Learn/images/GUID-5EB4DE0F-BF10-45D3-AB24-558C7EEA8800.png
P.S.: advanced will be simple dynamic viewport scale bar in main window, that will be placed in right-down corner.

**Comment by whitequark** [comment]
Out of scope. Use LibreCAD to prepare drawings, for foreseeable future.
