### ISSUE TITLE
[BUG] Crash when open any assembly examples

### ISSUE THREAD

**Issue by Symbian9** [whitequark/solvespace#50]
I use latest SolveSpace nightly relise from github (where "libslvs" for this build?), but when it try open any "asm.slvs" distributed on official site in Examples section and some examples on github (I unpack all files for assembly in same folder), it crashed with next error in bash:
<code>oops at line 706, file /home/travis/build/whitequark/solvespace/src/entity.cpp

Aborted</code>

P.S.: previouse build from Launchpad ( ver.2.1~trusty11 for solvespace and libslvs) open it normally.

**Comment by whitequark** [comment]
cc @Evil-Spirit

**Comment by Evil-Spirit** [comment]
fixed at https://github.com/Evil-Spirit/solvespace/commit/02be1d4ca4438ea405141a18c77504524b6707d3

**Comment by Symbian9** [comment]
Please, make new binary (solvespace&libslvs) from latest sources with bug fixes for Ubuntu 14. 04(x86 & x86_64) on Launchpad! Thanks.
