### ISSUE TITLE
Adding/removing point to existing spline

### ISSUE THREAD

**Issue by whitequark** [whitequark/solvespace#54]
See http://solvespace.com/forum.pl?action=viewthread&parent=430
Also, it should probably be possible to have more than ten.
- [x] Adding
- [x] Removing

**Comment by whitequark** [comment]
Fixed in 0939d851 and db4a3185c.

**Comment by whitequark** [comment]
Okay, we need to do something with constraints. Currently if the points are used in any constraints they get really messed up.

**Comment by whitequark** [comment]
@Evil-Spirit this doesn't seem to do anything.

**Comment by whitequark** [comment]
Oh, ReplacePointInConstraint only handles point-coincident constraints... hrm.

**Comment by whitequark** [comment]
@jwesthues Was there any particular reason for only touching point-coincident constraints in `ReplacePointInConstraints`?

**Comment by jwesthues** [comment]
No special reason; I think I just didn't want to bother testing all the constraints to confirm that there were no surprising special cases.

**Comment by whitequark** [comment]
Ah, OK. I'll remove the condition and test this, then (same for `FixConstraintsForPointBeingDeleted`).

**Comment by jwesthues** [comment]
Correct behavior for `FixConstraintsForPointBeingDeleted` may be less obvious. I added that because if you constrain points {A,B} and {B,C} coincident, it's surprising if after you delete point B, A and C are no longer constrained. I'm not sure there's an obvious analogy to that for other constraints.

**Comment by whitequark** [comment]
Right, I've just discovered that. The right behavior here is just to remove all non-point-coincident constraints related to the point being deleted, so I'll add another method on top of that.

**Comment by jwesthues** [comment]
That already happens in `SolveSpace::PruneConstraints` upon regeneration; so the only thing you'd gain from that is to make the "x constraints deleted" message disappear.

**Comment by whitequark** [comment]
The problem is that when we delete a point in the middle of a bezier, another one immediately takes its place (except in case of the first and last one), which causes the constraints to reapply to it, and distort the bezier in surprizing ways.

**Comment by jwesthues** [comment]
That makes sense. I'd forgotten we were talking about the spline thing and not deletion in general.

**Comment by whitequark** [comment]
Fixed in 9eaccea063 and 7f9b76cd5c9, now with constraints sticking to their respective points.
