### ISSUE TITLE
Resizing text browser crash SolveSpace

### ISSUE THREAD

**Issue by Symbian9** [whitequark/solvespace#58]
I often detect this bug in all SolveSpace version, but never post it here, so its time now.
Reproducing: 
1) run solvespace
2) goto "SolveSpace - Browser"
3) open "home" -> "line styles"
4) scroll to "background color (r, g, b)" and open "[change]"
5) while you see color chooser dialog, try enlarge it
6) ...crash!
System: LinuxMint amd64

DEBUG:
- in GDB
<code>(gdb) run
Starting program: /usr/bin/solvespace 
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
[New Thread 0x7fffeafce700 (LWP 24186)]
(solvespace:24182): glibmm-ERROR **: 
unhandled exception (type std::exception) in signal handler:
what: basic_string::_S_construct null not valid

Program received signal SIGTRAP, Trace/breakpoint trap.
0x00007ffff1f493c9 in g_logv () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
(gdb) bt
#0  0x00007ffff1f493c9 in g_logv () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#1  0x00007ffff1f49512 in g_log () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#2  0x00007ffff5a783af in Glib::exception_handlers_invoke() ()
   from /usr/lib/x86_64-linux-gnu/libglibmm-2.4.so.1
#3  0x00007ffff5a7e4cf in Glib::SignalProxyNormal::slot0_void_callback(_GObject*, void*) () from /usr/lib/x86_64-linux-gnu/libglibmm-2.4.so.1
#4  0x00007ffff220b188 in g_closure_invoke ()
   from /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#5  0x00007ffff221cdb1 in ?? ()
   from /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#6  0x00007ffff2224829 in g_signal_emit_valist ()
   from /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#7  0x00007ffff2224ae2 in g_signal_emit ()
   from /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#8  0x00007ffff642de8a in gtk_adjustment_value_changed ()
   from /usr/lib/x86_64-linux-gnu/libgtk-x11-2.0.so.0
#9  0x00000000004bf4a8 in SolveSpace::TextWindow::Paint() ()
#10 0x000000000044903a in SolveSpace::GlWidget::on_draw(Cairo::RefPtr<Cairo::Context> const&) ()
#11 0x000000000044b5c5 in SolveSpace::GlWidget::on_expose_event(_GdkEventExpose*) ()
#12 0x00007ffff7181c54 in Gtk::Widget_Class::expose_event_callback(_GtkWidget*, _GdkEventExpose*) () from /usr/lib/x86_64-linux-gnu/libgtkmm-2.4.so.1
#13 0x00007ffff64e2645 in ?? ()
   from /usr/lib/x86_64-linux-gnu/libgtk-x11-2.0.so.0
#14 0x00007ffff220b188 in g_closure_invoke ()
   from /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#15 0x00007ffff221c8db in ?? ()
   from /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#16 0x00007ffff22244f9 in g_signal_emit_valist ()
   from /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#17 0x00007ffff2224ae2 in g_signal_emit ()
   from /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#18 0x00007ffff65f25f4 in ?? ()
   from /usr/lib/x86_64-linux-gnu/libgtk-x11-2.0.so.0
#19 0x00007ffff64e1440 in gtk_main_do_event ()
   from /usr/lib/x86_64-linux-gnu/libgtk-x11-2.0.so.0
#20 0x00007ffff6143f2f in ?? ()
   from /usr/lib/x86_64-linux-gnu/libgdk-x11-2.0.so.0
#21 0x00007ffff6143ed5 in ?? ()
   from /usr/lib/x86_64-linux-gnu/libgdk-x11-2.0.so.0
#22 0x00007ffff6140b6e in ?? ()
   from /usr/lib/x86_64-linux-gnu/libgdk-x11-2.0.so.0
#23 0x00007ffff61415ed in gdk_window_process_updates ()
   from /usr/lib/x86_64-linux-gnu/libgdk-x11-2.0.so.0
#24 0x00007ffff6600f68 in ?? ()
   from /usr/lib/x86_64-linux-gnu/libgtk-x11-2.0.so.0
#25 0x00007ffff71005d0 in Gtk::Container_Class::check_resize_callback(_GtkContainer*) () from /usr/lib/x86_64-linux-gnu/libgtkmm-2.4.so.1
#26 0x00007ffff220b3b7 in ?? ()
   from /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#27 0x00007ffff2223e82 in g_signal_emit_valist ()
   from /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#28 0x00007ffff2224ae2 in g_signal_emit ()
   from /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#29 0x00007ffff6469ee0 in ?? ()
   from /usr/lib/x86_64-linux-gnu/libgtk-x11-2.0.so.0
#30 0x00007ffff6120cf7 in ?? ()
   from /usr/lib/x86_64-linux-gnu/libgdk-x11-2.0.so.0
#31 0x00007ffff1f423a6 in g_main_context_dispatch ()
   from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#32 0x00007ffff1f426f8 in ?? () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#33 0x00007ffff1f42afa in g_main_loop_run ()
   from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#34 0x00007ffff64e0277 in gtk_main ()
   from /usr/lib/x86_64-linux-gnu/libgtk-x11-2.0.so.0
#35 0x00007ffff712132d in Gtk::Main::run(Gtk::Window&) ()
   from /usr/lib/x86_64-linux-gnu/libgtkmm-2.4.so.1
#36 0x000000000042bb53 in main ()
(gdb)</code>
- in Terminal
<code> ~ $ solvespace
(solvespace:24248): glibmm-ERROR **: 
unhandled exception (type std::exception) in signal handler:
what: basic_string::_S_construct null not valid
Trace/breakpoint trap</code>

**Comment by whitequark** [comment]
Thanks, fixed in ef5db2132.
