### ISSUE TITLE
UI improvements + "lathe.png"

### ISSUE THREAD

**Issue by Symbian9** [whitequark/solvespace#59]
Think, SolveSpace need reorganise buttons in main window.
Also I paint "lathe.png".
<img src="http://pasteall.org/pic/show.php?id=97698">
Here you can see my proposition to main window UI.
<img src="http://pasteall.org/pic/show.php?id=97697">
I'm author of "lathe.png" icon and licensed it as PublicDomain image.

**Comment by whitequark** [comment]
That is a good icon, thanks a lot.

**Comment by Symbian9** [comment]
@whitequark, can you implement it in next nightly build?

**Comment by whitequark** [comment]
Done in 30d9bb0.
