### ISSUE TITLE
New constraint kind: line tangent to a circle

### ISSUE THREAD

**Issue by whitequark** [whitequark/solvespace#61]
Not sure if it's very important, since this can be emulated with one construction line.

**Comment by Symbian9** [comment]
Good idea! Think solvespace must have this.
Maybe, also need "Perpendicular" at point for  line connected to circle, arc and spline.

**Comment by whitequark** [comment]
So, hm, I've thought this over and both tangent and perpendicular to circle and arc anyhow requires a datum point to construct, by which point you are better off using a parallel or perpendicular constraint and a construction segment from center to a point on arc.

Perpendicular to bezier is necessary, but it can't be done without https://github.com/whitequark/solvespace/issues/52.
