### ISSUE TITLE
Add anti-aliasing to text rendering

### ISSUE THREAD

**Issue by Symbian9** [whitequark/solvespace#66]
Is it a way add anti-aliasing only to text rendering in main SolveSpace window using next tricks without make new lib dependency?(maybe try "multisampling")
1) http://stackoverflow.com/questions/27843294/glut-opengl-multisampling-anti-aliasing-msaa
2) https://www.opengl.org/discussion_boards/showthread.php/175076-Anti-aliasing-with-GLUT
3) http://stackoverflow.com/questions/4112106/anti-aliasing-in-opengl
4) https://www.mapbox.com/blog/drawing-antialiased-lines/

**Comment by whitequark** [comment]
The text is already antialiased.
![x](https://cloud.githubusercontent.com/assets/54771/13168028/98f2dc04-d6d0-11e5-8722-13adbbaf6788.png)
