### ISSUE TITLE
Builtin vector font needs grid-fitting

### ISSUE THREAD

**Issue by whitequark** [whitequark/solvespace#67]
![1930-1](https://cloud.githubusercontent.com/assets/54771/13547276/afa9c09e-e2c3-11e5-853e-7a828a1bf011.png)

**Comment by Evil-Spirit** [comment]
@whitequark, can you provide more information about this issue?

**Comment by whitequark** [comment]
You need to ensure that, in screen pixel coordinates, every point in the vector font has integer coordinates when the font size is less than 12pt. Just round it to nearest integer.

**Comment by Evil-Spirit** [comment]
I don't really think what this make it better, just bring more problems. We can't break subpixel accuracy because we have arbitrary dynamic projection, so performing it will cause much more visual artifacts.

**Comment by whitequark** [comment]
Of course it will, grid fitting is a standard technique.

**Comment by whitequark** [comment]
I actually implemented a simple version of this, but it broke because it did not consider `SS.GW.scale`, the font rendering code is pretty annoying there.

**Comment by Evil-Spirit** [comment]
It will cause visual flickering of text while the panning and rotation of view, i think it is the same kind of evil. The only point to apply it - while the exporting image.

**Comment by whitequark** [comment]
Why would it? Do you see any flickering while a browser is scrolling? I don't understand; simply panning text in increments of one pixel is enough.

**Comment by whitequark** [comment]
Basically, try it yourself: implement a hardcoded version that works only at one scale and you'll see that it looks just fine while panning.

**Comment by Evil-Spirit** [comment]
OK, i will try

**Comment by Evil-Spirit** [comment]
Without fitting
![not-grid-aligned](https://cloud.githubusercontent.com/assets/1980537/14279975/c6be60f4-fb51-11e5-9ff4-4d73389c10ee.png)

With fitting (looks ugly)
![grid-aligned](https://cloud.githubusercontent.com/assets/1980537/14279974/c6bd499e-fb51-11e5-9788-c5d07736e8f0.png)

**Comment by Evil-Spirit** [comment]
Actually it needs more powerful font-hinting algorithms.

**Comment by ruevs** [comment]
"With fitting (looks ugly)" actually looks much better to me.

**Comment by whitequark** [comment]
@Evil-Spirit It looks worse on larger font sizes. That's completely expected, really. But it should look better on 12pt and below, where the more 'blocky' nature of the letters is nowhere to be seen.

**Comment by Evil-Spirit** [comment]
without fitting
![font-fitting-original](https://cloud.githubusercontent.com/assets/1980537/14307277/91a224ac-fbef-11e5-823f-e59554f94ea6.png)
each vertex of font
![font-fitting-all](https://cloud.githubusercontent.com/assets/1980537/14307275/91a1acfc-fbef-11e5-93ae-fbbb15c3c9ff.png)
glyph bounds
![font-fitting-bound](https://cloud.githubusercontent.com/assets/1980537/14307276/91a1e0d2-fbef-11e5-8ee0-a6a626267f40.png)

Which is better?

**Comment by whitequark** [comment]
Hmmm. What if we grid fit only vertical/horizontal strokes?

**Comment by Evil-Spirit** [comment]
I've tried it, but it needs real curves instead of approximating segments. The true type font-hinting is always hand-work(https://www.typotheque.com/articles/hinting, http://alistapart.com/column/font-hinting-and-the-future-of-responsive-typography). The more i can do - grid-fit lower-case level of glyphs (now only fit common bound of captial letters - zero level, height level and horizontal bounds(min max))

**Comment by Evil-Spirit** [comment]
I think the last image is better.

**Comment by ruevs** [comment]
The last one ("glyph bounds") looks best to me as well. The smallest size is almost readable and the larger ones look the best - both in Latin and Cyrillic. I made a side-by-side image to compare easier.
![sidebyside](https://cloud.githubusercontent.com/assets/15338069/14309275/0e1cb396-fbe4-11e5-9081-23b68c8d165d.png)

"ех, чужд кайф: сплющь..." nice one :-)

**Comment by whitequark** [comment]
Can we do real curves? The source data, I.e. lff files, specify arcs explicitly, it makes sense to convert them to pwl in the font renderer.

**Comment by Evil-Spirit** [comment]
The main problem is make hand work, with automatic hinting we can't get the best quality

**Comment by whitequark** [comment]
Freetype's autohinter works quite well, and I don't see why we can't do it as well.

**Comment by Evil-Spirit** [comment]
The llf uses arcs, we have to convert them to bezier anyway (we need to arrange derivatives too). I don't see why we need it now, the font looking much better, i think it's enough. In other hand, if want to be best in font rendering, we can use free type renderer.

**Comment by Evil-Spirit** [comment]
Actually we also need to align width of each glyph (bounds) and interval between glyphs (to ensure each character has the same width at each string position.). I think it's not the problem, when we need to do 2d rendering (when text nerver goes 3d), when we need both (like comment in plane) we can't do it, because of ugly jittering.

**Comment by Evil-Spirit** [comment]
![phase](https://cloud.githubusercontent.com/assets/1980537/14346554/99cfc9e6-fcd4-11e5-8c41-67a9bcd82b17.png)

**Comment by Evil-Spirit** [comment]
http://www.paratype.com/services/truetypehinting.pdf

**Comment by whitequark** [comment]
When text goes 3d then just don't do any hinting, it's OK

**Comment by Evil-Spirit** [comment]
With aligning of widths and intervals, It will jump dramatically (can become 1.5 - 2 times shorter)

**Comment by whitequark** [comment]
Yes. That's the cost of doing business, so to say.

**Comment by Evil-Spirit** [comment]
If we want commented table-stamps for good appearance and printing, we just want to have same-string-lengths in view port and after the export. The EPS and PDF are drirectly-printing formats(executes inside printers and plotters), so we have to ensure the same appearance.

**Comment by whitequark** [comment]
Well, this is problematic... PDF export doesn't really need hinting, since printers with less than 300dpi don't exist and as such hinting is pointless. Note that this problem remains even if we use Freetype.

**Comment by Evil-Spirit** [comment]
Yes, this problem will be the same. So, i think, solvespace is not about observing details inside viewport so much, it's about designing and output for drawings (dxf, pdf, printer) or manufacturing (step, stl).

**Comment by whitequark** [comment]
It's both. You can even do manufacturing with a CAD-only workflow, which at no point involves drawings (but SolveSpace is nowhere near supporting that yet).

**Comment by Evil-Spirit** [comment]
@whitequark , don't forget what I insist on https://github.com/Evil-Spirit/solvespace/commit/a588a02b512db1a7659a42ef9e4a84c08c857475

**Comment by Evil-Spirit** [comment]
@whitequark, and we can use this approach to make text constants(like capital, letter, overall height) https://github.com/whitequark/solvespace/compare/for-upstream...Evil-Spirit:font-grid-67#diff-6fc5e64f1f4fa1e5646c890ced044a17R334

**Comment by whitequark** [comment]
Yeah, I remember about that one. How much larger does it make the compiled binary?

**Comment by Evil-Spirit** [comment]
Not so large. I actully dont remember, but i checked it

**Comment by whitequark** [comment]
@Evil-Spirit I've just tested your solution and results in extremely high quality rendering, on a wide range of font sizes starting from 6px. This is much better than what I expected. Thanks!

**Comment by whitequark** [comment]
Fixed in e74ccb301071. And I also made lff2c automatically compute the rest of the font metrics.
