### ISSUE TITLE
Automatic constraints can cause issues

### ISSUE THREAD

**Issue by marcbritten** [whitequark/solvespace#68]
Creating new geometry where the segments terminate on a line or point causes constraint issues when the program also generates an automatic H or V constraint.

I would recommend dropping the automatic constraint if both points of a segment are constrained already.

**Comment by whitequark** [comment]
Can you show an example sketch? Constraining a segment horizontally or vertically makes sense even if both ends are constrained, e.g. try drawing a rectangle.

**Comment by marcbritten** [comment]
Create a rectangle, then extrude it.  Now place a line segment between two points in a way that creates a horizontal constraint as well.

**Comment by whitequark** [comment]
Yes, I see the problem you're talking about. However, I maintain that adding an automatic constraint is useful even when both ends of a segment end up constrained to something else. Can we solve this problem in some other way? E.g. `Ctrl` turning off the autoconstrainter temporarily?

**Comment by whitequark** [comment]
Ok, yeah, I've started hitting this problem a lot. I think I'll turn it off if `Ctrl` is pressed, as a solution.

**Comment by Evil-Spirit** [comment]
The real solution should be based on dof analyzing, but it might be problematic. Should I introduce ctrl key?

**Comment by whitequark** [comment]
Yes.

**Comment by whitequark** [comment]
Fixed in 3d334d1.
