### ISSUE TITLE
Toolbar UI improvements

### ISSUE THREAD

**Issue by Symbian9** [whitequark/solvespace#71]
Here is my proposition for better ergonomic UI.
http://pasteall.org/pic/show.php?id=100349

**Comment by whitequark** [comment]
What do these icons even mean?

**Comment by Symbian9** [comment]
In this proposition no any new icons, but only present reorganized icon toolbar.

**Comment by whitequark** [comment]
No. The 1st section creates requests, the 2nd section creates constraints, the 3rd section creates groups. Everything is already sensible, and what you suggest would create confusion instead.
