### ISSUE TITLE
Could NOT find SPACEWARE

### ISSUE THREAD

**Issue by avh-on1** [whitequark/solvespace#72]
Building from git repo (6e56b00b9ae30b31df677cbe8fefdfef7edb7ad7) on Fedora 23, cmake returns this error:

`-- Could NOT find SPACEWARE (missing:  SPACEWARE_LIBRARY SPACEWARE_INCLUDE_DIR) `

**Comment by whitequark** [comment]
Do you want to use a SpaceWare input device?

**Comment by avh-on1** [comment]
Nope

**Comment by whitequark** [comment]
It's not a fatal error and won't prevent you from building SolveSpace.

**Comment by avh-on1** [comment]
Also, I do have libspnav-devel

**Comment by whitequark** [comment]
This is what I have in `FindSpaceWare.cmake`:

```
    find_path(SPACEWARE_INCLUDE_DIR
        spnav.h)

    find_library(SPACEWARE_LIBRARY
        NAMES spnav libspnav)
```

Are these header and library in your system include and library paths?

**Comment by avh-on1** [comment]
I have

    /usr/lib64libspnav.so
    /usr/include/spnav.h
    /usr/lib64/libspnav.so

**Comment by whitequark** [comment]
Can you pastebin the content of `CMakeFiles/CMakeOutput.log` in the build directory?

**Comment by avh-on1** [comment]
[here you go](http://pastebin.com/x2wtmpDX)

**Comment by whitequark** [comment]
Also `CMakeError.log`?

**Comment by avh-on1** [comment]
Rebooted my computer overnight.
`-- Found SPACEWARE: /usr/lib64/libspnav.so`
Sigh... thanks for the prompt assistance.
