### ISSUE TITLE
"New Group -> Frustum"

### ISSUE THREAD

**Issue by Symbian9** [whitequark/solvespace#73]
Can you add some option to "Extrusion" operation or make new "Frustum" operation for possibility to create pyramidal frustum in SolveSpace?
https://en.wikipedia.org/wiki/Frustum

**Comment by Evil-Spirit** [comment]
@whitequark,
@jwesthues.

I have idea about this: We can introduce new kind of useful operation - "Loft Extrusion".
1. We need to create some number of sketches, shifed along extrusion vector.
2. We consider them as step and repeat in sense of disabled ability to remove/add entities (and change topology by removing/adding PC-constraints).
3. We make separate set of parameters for them and make ability to introduce new constraints( excluding p.2) for make alility to change each sketch separately.
4. We can easily create NURBS body for it using the current functionality.

The useful usecases:
1. Frustum groups (something like, but not 100% of cases)
2. Airplane wings with complex profile.

**Comment by Evil-Spirit** [comment]
@whitequark, I've learn some book about NURBS, booleans and so on. For creating true frustum he fistly have to do equidistant for sketch (which exist in SketchFlat).

**Comment by whitequark** [comment]
@Evil-Spirit what do you mean by equidistant? don't we have that already?

**Comment by Evil-Spirit** [comment]
@whitequark 
I mean "offset" http://cq.cx/sketchflat.pl

**Comment by whitequark** [comment]
@Evil-Spirit why? cannot we just scale the sketch?

**Comment by Evil-Spirit** [comment]
@whitequark, It was my first thought, but this is geometrically wrong.

**Comment by whitequark** [comment]
@Evil-Spirit why? can you show an example?

**Comment by Evil-Spirit** [comment]
![2016-12-07 23 37 10](https://cloud.githubusercontent.com/assets/1980537/20976768/251f3f24-bcd6-11e6-8cf5-e89f92bdef4c.png)

**Comment by Evil-Spirit** [comment]
@whitequark,
Imagine bottom sketch as scaled. This is not the same.

**Comment by Evil-Spirit** [comment]
I made sketch offset and top looks like exactly the same
![2016-12-07 23 40 29](https://cloud.githubusercontent.com/assets/1980537/20977073/f9cadabc-bcd6-11e6-923d-a7251e55b7f0.png)

**Comment by Evil-Spirit** [comment]
@whitequark 
I am reading this book https://www.amazon.com/Geometric-Modeling-mathematics-Nikolay-Golovanov/dp/1497473195

**Comment by whitequark** [comment]
@Evil-Spirit I thought a frustum is a section of a pyramid. But the solid above wouldn't become a pyramid if you shrank the top sketch towards the limit of 0 in area, no?

**Comment by whitequark** [comment]
@Evil-Spirit Anyway. To support offset groups we'll need to derive entities, but we have degenerate cases where there are fewer entities in the output than in input. What do we do in this case?

**Comment by Evil-Spirit** [comment]
@whitequark I think we can just generate zero-length entities and skip them while processing of result sketch

**Comment by whitequark** [comment]
I've decided that adding new solid operations is less of a priority than migrating to the new file format and hierarchical sketches. At some point we will probably add the "loft extrusion" operation @Evil-Spirit is suggesting, but not very soon.
