### ISSUE TITLE
"Paste mirrored" and "Paste rationed" (2D sketch)

### ISSUE THREAD

**Issue by Symbian9** [whitequark/solvespace#75]
Sometime when you near complete detailed drawing and constrained it you apologize that it must be... mirrored. So, for solve this problem it will be good make option to "Copy -> Paste mirrored" with choosing axis
Next usefull future would be "Copy -> Paste rationed" that will paste copied sketch full rationed to parental.

**Comment by whitequark** [comment]
Edit → Paste Transformed... can do it.

**Comment by Symbian9** [comment]
This is not intuitive and it have NOT "mirror" future.

**Comment by whitequark** [comment]
Set scale to -1.

**Comment by ryannining** [comment]
i have issue too, while we can use new group rotate by a point and line to do mirror. But the resulted sketch have inverted normal axis so it cannot be extruded.

I think a new Mirror (new group or paste) will do. I wish i can do coding to help you guys.

**Comment by whitequark** [comment]
@ryannining Sure it can be extruded. See the following file for an example of how to do it:
[mirror.zip](https://github.com/whitequark/solvespace/files/346753/mirror.zip)

**Comment by ryannining** [comment]
thanks, it work

**Comment by whitequark** [comment]
https://github.com/solvespace/solvespace/issues/227
