### ISSUE TITLE
New plane thru one line and one point that not on this line

### ISSUE THREAD

**Issue by Symbian9** [whitequark/solvespace#76]
For now "New group in new workplane" say that its need one point and two line segments.
But, think, it will be good if you add possibility make new group in workplane also thru one line segment and one point, that not on it.
https://en.wikipedia.org/wiki/Playfair's_axiom
<i>"In a plane, given a line and a point not on it, at most one line parallel to the given line can be drawn through the point."</i>
Also known as:
<i>"There is only one plane that can be given thru line and a point not on it"</i>

**Comment by whitequark** [comment]
That can be trivially achieved with one construction segment, so no.
