### ISSUE TITLE
"Paste Transformed" on right mouse button

### ISSUE THREAD

**Issue by Symbian9** [whitequark/solvespace#77]
For now when something copied and than click right mouse button there is only "Paste" tab.
Please, add in this contextutal menu one more tab with "Paste Transformed" option.

**Comment by whitequark** [comment]
I don't think there is any point in this, given that even "Paste" doesn't take mouse position into account (maybe it should); for "Paste Transformed" the position is fully determined by the settings you enter in the text window, so the context menu option doesn't add anything of value.

**Comment by Symbian9** [comment]
But right button tab is more ergonomic and quicker than "Ctrl+T" or "Menu -> Edit -> Paste Transformed..." way.
In SolveSpace use right mouse button must be preferable, and short keys and menu tabs are additional.

**Comment by whitequark** [comment]
What? You can't do almost anything through RMB.

**Comment by Symbian9** [comment]
For now RMB already have many option:
- Assign to Style
- Group Info
- Style Info
- Select Edge Chain
- Cut
- Copy
- Paste
- Delete
- Unselect All
- Unselect Hovered
So, as for me as for "mouse user" right button menu and icon tabs menu is preferable than short key assigns.

**Comment by whitequark** [comment]
Yes. This is a very small subset of operations, most of which have something to do with the entity under cursor.

**Comment by Symbian9** [comment]
So, what a problem add "Paste Transformed" to this list?

**Comment by whitequark** [comment]
e87e787.

**Comment by Symbian9** [comment]
Thank You!
