### ISSUE TITLE
When creating a new group, use the same color as the last requested geometry

### ISSUE THREAD

**Issue by whitequark** [whitequark/solvespace#83]

**Comment by whitequark** [comment]
Fixed in 839335a.

**Comment by whitequark** [comment]
Hm, we should use not the very last group but the group the new group is based on, in case we're inserting into the middle of the stack.

**Comment by Evil-Spirit** [comment]
Don't consider it.

**Comment by whitequark** [comment]
Fixed in b80dfaa.
