### ISSUE TITLE
Wrong constraint set is exported to DXF

### ISSUE THREAD

**Issue by whitequark** [whitequark/solvespace#85]
Constraints in non-last groups are exported.

**Comment by Evil-Spirit** [comment]
I think it is need to make a checkbox for showing/exporting constraints for choosen groups like it is performed now for an entities.

**Comment by whitequark** [comment]
No. At some point there should be a separate drawing module. Before that let's keep it simple.

**Comment by Symbian9** [comment]
I also think about this future. As for me, it will be good if constraints will have two additional inbuild styles:
 1) s00e-#def-constraint-printed
 2) s00f-#def-constraint-not-printed

Think it would be simpler than make additional checkboxes.
Also it will add possibility customise different constraints.

Another way is add "Toggle construction" option applied to constraints too.

**Comment by whitequark** [comment]
Fixed in e17a2481.
