### ISSUE TITLE
Translating to other language

### ISSUE THREAD

**Issue by Symbian9** [whitequark/solvespace#88]
Think its a time now to prepare SolveSpace for translating to other language.
As for me, it will be cool if language file would be simple text file (like "solvespace_de.txt"), with next structure:

HEADER_WITH_LANG_CODE_AND_VERSION
SOURCE_STRING1    #TRANSLATED_STRING1
SOURCE_STRING2_ROW1\nROW2    #TRANSLATED_STRING2_ROW1\nROW2
...

**Comment by whitequark** [comment]
That's not really possible due to the way the text window is programmed.

**Comment by whitequark** [comment]
Migrated to https://github.com/solvespace/solvespace/issues/112.
