### ISSUE TITLE
Do not apply line styles to axis indicator

### ISSUE THREAD

**Issue by Symbian9** [whitequark/solvespace#89]
For now, if select border of any plane and "Assign Newly Created Style" it also apply line style to axis indicator (that placed in left-down corner of main window).
So if apply to border of plane "waved" line stile then one of axis also will be "waved".
Screenshot - http://pasteall.org/pic/show.php?id=100741

**Comment by Evil-Spirit** [comment]
Should i get it work properly or just ban planes from ablility to specify styles for them?

**Comment by whitequark** [comment]
I don't see any point in specifying styles for planes.

**Comment by whitequark** [comment]
Fixed in 73f28b9.
