### ISSUE TITLE
Exporting Three.js viewer with scale factor != 1 results in edges out of scale

### ISSUE THREAD

**Issue by whitequark** [whitequark/solvespace#90]

**Comment by Evil-Spirit** [comment]
@whitequark  can you provide more info how to reproduce this?

**Comment by whitequark** [comment]
Draw any mesh. Set export scale to e.g. 1:3.

Then export triangle mesh, then select Three.js with viewer as the format. The file can be opened in browser. You'll see that both the (pwl) edges and the mesh are drawn but they do not match.

**Comment by whitequark** [comment]
Fixed in 46b67d5.
