### ISSUE TITLE
Inbuild color themes

### ISSUE THREAD

**Issue by Symbian9** [whitequark/solvespace#93]
This is minor future request for making at least 3 inbuild themes, that can be easely switched in "line styles" menu:
1) "default" - that is now presented (black background & and standart line colors)
2) "paper" - near like it will look on paper (white background & all lines black)
3) "blueprint" - that is standart for USA (blue background & and all lines silver)

And, of course, its steal possible to set all colors manually or clear them to "default" theme.

P.S.: Also I remember "NotSolveSpace" color scheme that look good
http://solvespace.com/forum.pl?action=viewthread&parent=533

**Comment by whitequark** [comment]
> 3) "blueprint" - that is standart for USA (blue background & and all lines silver)

No one actually uses this.

Otherwise, no. At some point there will be a proper separate export preview / drawing mode, which will do what you want.
