### ISSUE TITLE
Stipple line type ignored when try export to PDF or other

### ISSUE THREAD

**Issue by Symbian9** [whitequark/solvespace#96]
When I try export drawing that include dashed lines or other types its always export only as it was single type.

**Comment by whitequark** [comment]
PDF/EPS done in 94cba11.

**Comment by Symbian9** [comment]
Stippled lines in 2016.04.08 nightly build have an issues:
Testing - https://github.com/whitequark/solvespace-testcases/tree/master/tests/stippled

1) if export scale 1:1.0000
* 1st line hase 10 segments instead to 5 (but in SolveSpace I see really 5, not 10). All other styles also hase doubled number of needing segments

2) if export scale 1:0.500
* all Ok, first line and all other have same number as it described in comments

3) if export scale 1:2.000
* all Ok, first line and all other have same number as it described in comments

**Comment by Evil-Spirit** [comment]
Please, report additional info about file type and viewer

**Comment by Evil-Spirit** [comment]
@Symbian9, please, say which filetype, os, and viewer do you use.

**Comment by whitequark** [comment]
SVG done in 4a748166e.
