### ISSUE TITLE
Improve Three.js controls

### ISSUE THREAD

**Issue by whitequark** [whitequark/solvespace#98]
Need to integrate the changes by @cr1901 here: https://github.com/cr1901/solvespace.js

**Comment by cr1901** [comment]
I will write a script to automate export (to the extent possible). Thoughts on linking my repo as a submodule so that we have an easy ID to figure out which version of the code is in Solvespace? Or perhaps as a post-commit hook, I'll stamp the code with the version in case bug fixes are needed.

**Comment by whitequark** [comment]
Nah, no submodules, too complex. I'll write an asset system for SolveSpace at some point, but not yet.

**Comment by cr1901** [comment]
Okay cool, I'll just make a post-commit hook to stamp the classes with a version ID variable for now. So if you or anyone has any bugs to report, I can figure (more) quickly which commit to look at.

**Comment by whitequark** [comment]
@cr1901 This is completely broken. Dragging the left mouse button does not rotate the model, and right mouse button now brings up a popup menu instead of dragging the model.

**Comment by cr1901** [comment]
@whitequark As a consequence of removing OrthographicTrackballControls, middle mouse click now rotates the model to match Solvespace behavior. Want me to change it back to the way it was?

This idea was if you right click without moving the mouse at all a context menu will be brought up in case you still needed it. I must've implemented this improperly, so I'll get rid of it.

**Comment by Evil-Spirit** [comment]
@cr1901 I think we have to consider touch-screen cases, so the SolveSpace's behaviour seems to be useless.

**Comment by cr1901** [comment]
@Evil-Spirit Whitequark and I have been talking on IRC, and I agree. This was an accessibility fail for me.

Even without considering touch events, the controls as-is only work properly with a USB mouse (which is what I primarily use- oops!).

**Comment by whitequark** [comment]
All seems OK, testing now.

**Comment by whitequark** [comment]
Fixed in affc88f3.
